-- Fase 13.11: links seguros, confirmação idempotente, reagendamento atômico
-- e cancelamento com política de estorno e cancelamento de lembretes.

create extension if not exists pgcrypto with schema extensions;

alter table public.agendamentos
  add column if not exists site_access_token_expires_at timestamptz,
  add column if not exists site_access_token_use_count integer not null default 0,
  add column if not exists confirmacao_origem text,
  add column if not exists cancelamento_origem text,
  add column if not exists cancelado_por_cliente bigint,
  add column if not exists cancelado_por_usuario uuid;

update public.agendamentos
set site_access_token_expires_at = greatest(
  coalesce(site_access_token_expires_at, now() + interval '90 days'),
  now() + interval '7 days'
)
where site_access_token is not null
  and site_access_token_expires_at is null;

alter table public.agendamentos
  alter column site_access_token_expires_at set default (now() + interval '90 days');

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'agendamentos_site_access_token_use_count_check'
      and conrelid = 'public.agendamentos'::regclass
  ) then
    alter table public.agendamentos
      add constraint agendamentos_site_access_token_use_count_check
      check (site_access_token_use_count >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'agendamentos_confirmacao_origem_check'
      and conrelid = 'public.agendamentos'::regclass
  ) then
    alter table public.agendamentos
      add constraint agendamentos_confirmacao_origem_check
      check (confirmacao_origem is null or confirmacao_origem in (
        'link_cliente', 'area_cliente', 'pagamento_mercado_pago', 'equipe', 'sistema'
      ));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'agendamentos_cancelamento_origem_check'
      and conrelid = 'public.agendamentos'::regclass
  ) then
    alter table public.agendamentos
      add constraint agendamentos_cancelamento_origem_check
      check (cancelamento_origem is null or cancelamento_origem in (
        'link_cliente', 'area_cliente', 'equipe', 'expiracao_pagamento', 'sistema'
      ));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'agendamentos_cancelado_por_cliente_fkey'
      and conrelid = 'public.agendamentos'::regclass
  ) then
    alter table public.agendamentos
      add constraint agendamentos_cancelado_por_cliente_fkey
      foreign key (id_empresa, cancelado_por_cliente)
      references public.clientes(id_empresa, id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'agendamentos_cancelado_por_usuario_fkey'
      and conrelid = 'public.agendamentos'::regclass
  ) then
    alter table public.agendamentos
      add constraint agendamentos_cancelado_por_usuario_fkey
      foreign key (cancelado_por_usuario)
      references auth.users(id) on delete set null;
  end if;
end;
$$;

create table if not exists public.tokens_links_agendamento (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_agendamento bigint not null,
  token_hash text not null,
  finalidade text not null default 'gerenciar',
  expira_em timestamptz not null,
  max_usos smallint not null default 5,
  usos smallint not null default 0,
  ultimo_uso_em timestamptz,
  revogado_em timestamptz,
  created_at timestamptz not null default now(),
  constraint tokens_links_agendamento_agendamento_fkey
    foreign key (id_empresa, id_agendamento)
    references public.agendamentos(id_empresa, id) on delete cascade,
  constraint tokens_links_agendamento_hash_unique unique (token_hash),
  constraint tokens_links_agendamento_finalidade_check
    check (finalidade in ('gerenciar', 'confirmar')),
  constraint tokens_links_agendamento_usos_check
    check (max_usos between 1 and 20 and usos between 0 and max_usos)
);

create index if not exists tokens_links_agendamento_ativos_idx
  on public.tokens_links_agendamento (id_empresa, id_agendamento, finalidade, expira_em)
  where revogado_em is null;

create table if not exists public.solicitacoes_estorno_agendamento (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_agendamento bigint not null,
  id_pagamento bigint not null,
  valor numeric(12,2) not null,
  status text not null default 'pendente',
  motivo text not null,
  chave_idempotencia uuid not null default gen_random_uuid(),
  tentativas smallint not null default 0,
  proxima_tentativa_em timestamptz not null default now(),
  provedor_status text,
  provedor_status_detalhe text,
  ultimo_erro text,
  processado_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint solicitacoes_estorno_agendamento_fkey
    foreign key (id_empresa, id_agendamento)
    references public.agendamentos(id_empresa, id) on delete cascade,
  constraint solicitacoes_estorno_pagamento_fkey
    foreign key (id_empresa, id_pagamento)
    references public.pagamentos(id_empresa, id),
  constraint solicitacoes_estorno_valor_check check (valor > 0),
  constraint solicitacoes_estorno_status_check check (
    status in ('pendente', 'processando', 'confirmado', 'falhou', 'revisao_manual', 'cancelado')
  ),
  constraint solicitacoes_estorno_tentativas_check check (tentativas between 0 and 10),
  constraint solicitacoes_estorno_chave_unique unique (chave_idempotencia)
);

create unique index if not exists solicitacoes_estorno_pagamento_ativa_unique
  on public.solicitacoes_estorno_agendamento (id_empresa, id_pagamento)
  where status in ('pendente', 'processando', 'falhou', 'revisao_manual');

create index if not exists solicitacoes_estorno_processamento_idx
  on public.solicitacoes_estorno_agendamento (status, proxima_tentativa_em, id)
  where status in ('pendente', 'falhou');

alter table public.tokens_links_agendamento enable row level security;
alter table public.solicitacoes_estorno_agendamento enable row level security;

drop policy if exists tokens_links_agendamento_equipe_le on public.tokens_links_agendamento;
create policy tokens_links_agendamento_equipe_le
on public.tokens_links_agendamento for select to authenticated
using (private.usuario_pertence_empresa(id_empresa));

drop policy if exists solicitacoes_estorno_equipe_le on public.solicitacoes_estorno_agendamento;
create policy solicitacoes_estorno_equipe_le
on public.solicitacoes_estorno_agendamento for select to authenticated
using (private.usuario_pertence_empresa(id_empresa));

revoke all on public.tokens_links_agendamento, public.solicitacoes_estorno_agendamento
  from public, anon, authenticated;
grant select on public.tokens_links_agendamento, public.solicitacoes_estorno_agendamento
  to authenticated;

create or replace function private.emitir_token_link_agendamento(
  p_id_empresa bigint,
  p_id_agendamento bigint,
  p_finalidade text default 'gerenciar',
  p_validade interval default interval '7 days'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_token text;
  v_expira_em timestamptz;
begin
  if p_finalidade not in ('gerenciar', 'confirmar') then
    raise exception 'Finalidade de token invalida.';
  end if;
  if p_validade < interval '5 minutes' or p_validade > interval '30 days' then
    raise exception 'Validade do token fora do intervalo permitido.';
  end if;

  perform 1 from public.agendamentos a
  where a.id_empresa = p_id_empresa and a.id = p_id_agendamento
  for update;
  if not found then raise exception 'Agendamento nao encontrado.'; end if;

  update public.tokens_links_agendamento
  set revogado_em = now()
  where id_empresa = p_id_empresa
    and id_agendamento = p_id_agendamento
    and finalidade = p_finalidade
    and revogado_em is null;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  v_expira_em := now() + p_validade;

  insert into public.tokens_links_agendamento (
    id_empresa, id_agendamento, token_hash, finalidade, expira_em
  ) values (
    p_id_empresa, p_id_agendamento,
    encode(extensions.digest(v_token, 'sha256'), 'hex'),
    p_finalidade, v_expira_em
  );

  return jsonb_build_object('token', v_token, 'expires_at', v_expira_em);
end;
$$;

create or replace function public.consumir_token_link_agendamento(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_link public.tokens_links_agendamento%rowtype;
  v_booking_token uuid;
begin
  if p_token is null or p_token !~ '^[0-9a-fA-F]{64}$' then
    raise exception 'Link de confirmacao invalido.';
  end if;

  select * into v_link
  from public.tokens_links_agendamento t
  where t.token_hash = encode(extensions.digest(lower(p_token), 'sha256'), 'hex')
  for update;

  if not found
     or v_link.revogado_em is not null
     or v_link.expira_em <= now()
     or v_link.usos >= v_link.max_usos then
    raise exception 'Este link expirou ou ja atingiu o limite de uso.';
  end if;

  select a.site_access_token into v_booking_token
  from public.agendamentos a
  where a.id_empresa = v_link.id_empresa
    and a.id = v_link.id_agendamento
    and a.site_access_token is not null
    and coalesce(a.site_access_token_expires_at, now() - interval '1 second') > now();

  if v_booking_token is null then
    raise exception 'O acesso a este agendamento expirou.';
  end if;

  update public.tokens_links_agendamento
  set usos = usos + 1, ultimo_uso_em = now()
  where id = v_link.id;

  return jsonb_build_object(
    'company_id', v_link.id_empresa,
    'booking_id', v_link.id_agendamento,
    'booking_token', v_booking_token,
    'expires_at', least(v_link.expira_em, now() + interval '7 days')
  );
end;
$$;

create or replace function private.cancelar_mensagens_agendamento(
  p_id_empresa bigint,
  p_id_agendamento bigint
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_total integer;
begin
  update public.fila_mensagens
  set status = 'cancelada', cancelada_em = now(), updated_at = now()
  where id_empresa = p_id_empresa
    and status in ('pendente', 'erro')
    and dados_template->>'agendamento_id' = p_id_agendamento::text;
  get diagnostics v_total = row_count;
  return v_total;
end;
$$;

create or replace function private.enfileirar_mensagem_agendamento(
  p_id_empresa bigint,
  p_id_agendamento bigint,
  p_tipo text,
  p_gerar_link boolean default true
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_agendamento public.agendamentos%rowtype;
  v_cliente public.clientes%rowtype;
  v_preferencias jsonb;
  v_emitido jsonb;
  v_link text;
  v_assunto text;
  v_conteudo text;
  v_chave text;
begin
  select * into v_agendamento
  from public.agendamentos a
  where a.id_empresa = p_id_empresa and a.id = p_id_agendamento;
  if not found then return; end if;

  select * into v_cliente
  from public.clientes c
  where c.id_empresa = p_id_empresa and c.id = v_agendamento.id_cliente;
  if not found then return; end if;

  v_preferencias := coalesce(v_agendamento.site_notification_preferences, '{}'::jsonb);
  if p_gerar_link then
    v_emitido := private.emitir_token_link_agendamento(
      p_id_empresa, p_id_agendamento, 'gerenciar', interval '7 days'
    );
    v_link := '/confirmacao/acessar?token=' || (v_emitido->>'token');
  end if;

  v_assunto := case p_tipo
    when 'reagendamento' then 'Seu novo horario foi reservado'
    when 'cancelamento' then 'Cancelamento do agendamento'
    else 'Confirme seu agendamento'
  end;
  v_conteudo := case p_tipo
    when 'reagendamento' then 'Seu agendamento foi reagendado. Confira os novos dados no link seguro.'
    when 'cancelamento' then 'Seu cancelamento foi registrado. Consulte os detalhes na sua area do cliente.'
    else 'Seu horario foi reservado. Use o link seguro para consultar e confirmar.'
  end;
  v_chave := p_tipo || ':' || p_id_agendamento::text || ':' ||
    coalesce(v_emitido->>'token', extract(epoch from clock_timestamp())::bigint::text);

  if coalesce((v_preferencias->>'email')::boolean, true)
     and nullif(btrim(v_cliente.email), '') is not null then
    insert into public.fila_mensagens (
      id_empresa, id_cliente, canal, destinatario, assunto, conteudo,
      dados_template, status, prioridade, agendada_para,
      tentativas, max_tentativas, chave_idempotencia
    ) values (
      p_id_empresa, v_cliente.id, 'email', lower(btrim(v_cliente.email)),
      v_assunto, v_conteudo,
      jsonb_build_object(
        'tipo', p_tipo, 'agendamento_id', p_id_agendamento,
        'inicio', v_agendamento.inicio, 'link_relativo', v_link,
        'token_expira_em', v_emitido->>'expires_at'
      ),
      'pendente', 100, now(), 0, 5, v_chave || ':email'
    );
  end if;

  if coalesce((v_preferencias->>'whatsapp')::boolean, true)
     and nullif(btrim(coalesce(v_cliente.telefone_e164, v_cliente.telefone_principal)), '') is not null then
    insert into public.fila_mensagens (
      id_empresa, id_cliente, canal, destinatario, assunto, conteudo,
      dados_template, status, prioridade, agendada_para,
      tentativas, max_tentativas, chave_idempotencia
    ) values (
      p_id_empresa, v_cliente.id, 'whatsapp',
      btrim(coalesce(v_cliente.telefone_e164, v_cliente.telefone_principal)),
      v_assunto, v_conteudo,
      jsonb_build_object(
        'tipo', p_tipo, 'agendamento_id', p_id_agendamento,
        'inicio', v_agendamento.inicio, 'link_relativo', v_link,
        'token_expira_em', v_emitido->>'expires_at'
      ),
      'pendente', 100, now(), 0, 5, v_chave || ':whatsapp'
    );
  end if;
end;
$$;

create or replace function private.enfileirar_confirmacao_novo_agendamento()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.ordem = 1 and new.status = 'reservado' then
    perform private.enfileirar_mensagem_agendamento(
      new.id_empresa, new.id_agendamento, 'confirmacao_agendamento', true
    );
  end if;
  return new;
end;
$$;

drop trigger if exists agendamentos_servicos_enfileirar_confirmacao on public.agendamentos_servicos;
create trigger agendamentos_servicos_enfileirar_confirmacao
after insert on public.agendamentos_servicos
for each row execute function private.enfileirar_confirmacao_novo_agendamento();

create or replace function private.obter_agendamento_site(p_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', a.id,
    'token', a.site_access_token,
    'codigo', 'MK' || lpad(a.id::text, 6, '0'),
    'status', a.status,
    'inicio', a.inicio,
    'fim', a.fim,
    'sinal_status', a.sinal_status,
    'sinal_valor', a.sinal_valor,
    'confirmado_em', a.confirmado_em,
    'confirmacao_origem', a.confirmacao_origem,
    'cancelado_em', a.cancelado_em,
    'motivo_cancelamento', a.motivo_cancelamento,
    'cancelamento_origem', a.cancelamento_origem,
    'estorno', (
      select jsonb_build_object('status', r.status, 'valor', r.valor)
      from public.solicitacoes_estorno_agendamento r
      where r.id_empresa = a.id_empresa and r.id_agendamento = a.id
      order by r.id desc limit 1
    ),
    'cliente', jsonb_build_object(
      'nome', c.nome, 'email', c.email, 'telefone', c.telefone_principal
    ),
    'empresa', jsonb_build_object(
      'id', e.id, 'nome', e.fantasia,
      'fuso_horario', coalesce(e.fuso_horario, 'America/Sao_Paulo')
    ),
    'servico', jsonb_build_object(
      'id', s.id, 'nome', s.nome,
      'duracao_minutos', item.duracao_minutos, 'preco', item.preco
    ),
    'profissional', jsonb_build_object(
      'id', f.id,
      'nome', regexp_replace(f.nome, '[[:space:]]*\(Teste\)[[:space:]]*$', '', 'i'),
      'cargo', coalesce(f.cargo, 'Profissional')
    ),
    'lembretes', coalesce(a.site_notification_preferences, '{}'::jsonb)
  )
  from public.agendamentos a
  join public.clientes c
    on c.id_empresa = a.id_empresa and c.id = a.id_cliente
  join public.empresas e on e.id = a.id_empresa
  join lateral (
    select i.* from public.agendamentos_servicos i
    where i.id_empresa = a.id_empresa and i.id_agendamento = a.id
    order by (i.status = 'cancelado'), i.ordem, i.id limit 1
  ) item on true
  join public.servicos s
    on s.id_empresa = item.id_empresa and s.id = item.id_servico
  join public.funcionarios f
    on f.id_empresa = item.id_empresa and f.id = item.id_funcionario
  where a.site_access_token = p_token
    and coalesce(a.site_access_token_expires_at, now() - interval '1 second') > now();
$$;

create or replace function private.aplicar_acao_agendamento_cliente(
  p_id_empresa bigint,
  p_id_agendamento bigint,
  p_acao text,
  p_motivo text,
  p_origem text,
  p_id_cliente bigint,
  p_usuario uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_agendamento public.agendamentos%rowtype;
  v_politica public.politicas_cancelamento%rowtype;
  v_pagamento public.pagamentos%rowtype;
  v_valor_estorno numeric(12,2);
  v_status_estorno text;
begin
  select * into v_agendamento
  from public.agendamentos a
  where a.id_empresa = p_id_empresa and a.id = p_id_agendamento
  for update;
  if not found then raise exception 'Agendamento nao encontrado.'; end if;

  if p_acao = 'confirmar' then
    if v_agendamento.status = 'confirmado' then return; end if;
    if v_agendamento.status not in ('aguardando_confirmacao', 'aguardando_pagamento') then
      raise exception 'Este agendamento nao pode ser confirmado.';
    end if;
    if v_agendamento.sinal_status = 'pendente' then
      raise exception 'O pagamento do sinal ainda esta pendente.';
    end if;
    if v_agendamento.inicio <= now() then
      raise exception 'Agendamentos passados nao podem ser confirmados.';
    end if;

    update public.agendamentos
    set status = 'confirmado',
        confirmado_em = coalesce(confirmado_em, now()),
        confirmacao_origem = p_origem,
        updated_at = now()
    where id_empresa = p_id_empresa and id = p_id_agendamento;
    return;
  end if;

  if p_acao <> 'cancelar' then raise exception 'Acao invalida.'; end if;
  if v_agendamento.status = 'cancelado' then return; end if;
  if v_agendamento.status in ('finalizado', 'no_show', 'em_atendimento') then
    raise exception 'Este agendamento nao pode mais ser cancelado.';
  end if;
  if char_length(coalesce(p_motivo, '')) > 500 then
    raise exception 'O motivo pode ter no maximo 500 caracteres.';
  end if;

  select * into v_politica
  from public.politicas_cancelamento p
  where p.id_empresa = p_id_empresa and p.ativo
    and current_date between p.vigente_desde and coalesce(p.vigente_ate, 'infinity'::date)
    and (p.id_unidade = v_agendamento.id_unidade or p.id_unidade is null)
  order by (p.id_unidade = v_agendamento.id_unidade) desc,
    p.vigente_desde desc, p.id desc limit 1;

  if v_agendamento.inicio <= now() + make_interval(
    mins => coalesce(v_politica.antecedencia_cancelamento_minutos, 1440)
  ) then
    raise exception 'O prazo para cancelamento online desta reserva ja terminou.';
  end if;

  update public.agendamentos
  set status = 'cancelado', cancelado_em = coalesce(cancelado_em, now()),
      motivo_cancelamento = coalesce(nullif(btrim(p_motivo), ''), 'Cancelado pelo cliente.'),
      cancelamento_origem = p_origem,
      cancelado_por_cliente = p_id_cliente,
      cancelado_por_usuario = p_usuario,
      updated_at = now()
  where id_empresa = p_id_empresa and id = p_id_agendamento;

  perform private.cancelar_mensagens_agendamento(p_id_empresa, p_id_agendamento);
  update public.tokens_links_agendamento
  set revogado_em = now()
  where id_empresa = p_id_empresa and id_agendamento = p_id_agendamento
    and revogado_em is null;

  update public.pagamentos
  set status = 'cancelado', updated_at = now(),
      observacoes = concat_ws(E'\n', observacoes, 'Cancelado junto com o agendamento antes do pagamento.')
  where id_empresa = p_id_empresa and id_agendamento = p_id_agendamento
    and status in ('pendente', 'processando');

  update public.agendamentos
  set pagamento_status = 'cancelado', updated_at = now()
  where id_empresa = p_id_empresa and id = p_id_agendamento
    and pagamento_status in ('pendente', 'processando', 'falhou');

  select * into v_pagamento
  from public.pagamentos p
  where p.id_empresa = p_id_empresa and p.id_agendamento = p_id_agendamento
    and p.status = 'confirmado'
  order by p.id desc limit 1 for update;

  if found and v_agendamento.sinal_status = 'pago' then
    v_valor_estorno := greatest(
      round(v_pagamento.valor - (
        v_agendamento.valor_total * coalesce(v_politica.multa_cancelamento_percentual, 0) / 100
      ), 2),
      0
    );
    if v_valor_estorno > 0 then
      v_status_estorno := case
        when v_valor_estorno <> v_pagamento.valor then 'revisao_manual'
        when v_pagamento.provedor = 'mercado_pago'
             and v_pagamento.identificador_externo is not null then 'pendente'
        else 'revisao_manual'
      end;
      insert into public.solicitacoes_estorno_agendamento (
        id_empresa, id_agendamento, id_pagamento, valor, status, motivo
      ) values (
        p_id_empresa, p_id_agendamento, v_pagamento.id, v_valor_estorno,
        v_status_estorno, 'Estorno solicitado conforme politica de cancelamento.'
      ) on conflict do nothing;
    end if;
  end if;

  perform private.enfileirar_mensagem_agendamento(
    p_id_empresa, p_id_agendamento, 'cancelamento', false
  );
end;
$$;

create or replace function private.alterar_agendamento_site(
  p_token uuid,
  p_acao text,
  p_motivo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_agendamento public.agendamentos%rowtype;
begin
  select * into v_agendamento
  from public.agendamentos a
  where a.site_access_token = p_token
    and coalesce(a.site_access_token_expires_at, now() - interval '1 second') > now()
  for update;
  if not found then raise exception 'O acesso a este agendamento expirou.'; end if;

  update public.agendamentos
  set site_access_token_use_count = site_access_token_use_count + 1
  where id_empresa = v_agendamento.id_empresa and id = v_agendamento.id;

  perform private.aplicar_acao_agendamento_cliente(
    v_agendamento.id_empresa, v_agendamento.id, p_acao, p_motivo,
    'link_cliente', v_agendamento.id_cliente, null
  );
  return private.obter_agendamento_site(p_token);
end;
$$;

create or replace function private.reagendar_agendamento_core(
  p_id_empresa bigint,
  p_id_agendamento bigint,
  p_id_funcionario bigint,
  p_inicio timestamptz,
  p_origem text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_agendamento public.agendamentos%rowtype;
  v_item public.agendamentos_servicos%rowtype;
  v_fuso text;
  v_disponivel boolean;
  v_fim timestamptz;
  v_antecedencia integer := 1440;
  v_novo_token uuid := gen_random_uuid();
  v_primeiro bigint;
  v_segundo bigint;
begin
  select * into v_agendamento from public.agendamentos a
  where a.id_empresa = p_id_empresa and a.id = p_id_agendamento for update;
  if not found then raise exception 'Agendamento nao encontrado.'; end if;
  if v_agendamento.status in ('cancelado', 'finalizado', 'no_show', 'em_atendimento') then
    raise exception 'Este agendamento nao pode mais ser reagendado.';
  end if;

  select coalesce(p.antecedencia_reagendamento_minutos, 1440) into v_antecedencia
  from public.politicas_cancelamento p
  where p.id_empresa = p_id_empresa and p.ativo
    and current_date between p.vigente_desde and coalesce(p.vigente_ate, 'infinity'::date)
    and (p.id_unidade = v_agendamento.id_unidade or p.id_unidade is null)
  order by (p.id_unidade = v_agendamento.id_unidade) desc,
    p.vigente_desde desc, p.id desc limit 1;
  if v_agendamento.inicio <= now() + make_interval(mins => coalesce(v_antecedencia, 1440)) then
    raise exception 'O prazo para reagendamento online desta reserva ja terminou.';
  end if;

  select * into v_item from public.agendamentos_servicos item
  where item.id_empresa = p_id_empresa and item.id_agendamento = p_id_agendamento
    and item.status <> 'cancelado'
  order by item.ordem, item.id limit 1 for update;
  if not found then raise exception 'Servico do agendamento nao encontrado.'; end if;

  v_primeiro := least(v_item.id_funcionario, p_id_funcionario);
  v_segundo := greatest(v_item.id_funcionario, p_id_funcionario);
  perform pg_advisory_xact_lock(hashtextextended(p_id_empresa::text || ':' || v_primeiro::text, 0));
  if v_segundo <> v_primeiro then
    perform pg_advisory_xact_lock(hashtextextended(p_id_empresa::text || ':' || v_segundo::text, 0));
  end if;

  update public.agendamentos_servicos set status = 'cancelado', updated_at = now()
  where id_empresa = v_item.id_empresa and id = v_item.id;

  select coalesce(u.fuso_horario, e.fuso_horario, 'America/Sao_Paulo') into v_fuso
  from public.unidades u join public.empresas e on e.id = u.id_empresa
  where u.id_empresa = p_id_empresa and u.id = v_agendamento.id_unidade;

  select exists (
    select 1 from jsonb_array_elements(private.obter_disponibilidade_site(
      p_id_empresa, v_agendamento.id_unidade,
      (p_inicio at time zone v_fuso)::date,
      v_item.id_servico, p_id_funcionario
    )) slot
    where (slot->>'id_funcionario')::bigint = p_id_funcionario
      and (slot->>'inicio')::timestamptz = p_inicio
  ) into v_disponivel;
  if not v_disponivel then
    raise exception using errcode = '23P01',
      message = 'Este horario nao esta mais disponivel. Escolha outro horario.';
  end if;

  v_fim := p_inicio + make_interval(mins => v_item.duracao_minutos);
  perform private.cancelar_mensagens_agendamento(p_id_empresa, p_id_agendamento);

  update public.agendamentos
  set inicio = p_inicio, fim = v_fim,
      site_access_token = v_novo_token,
      site_access_token_expires_at = now() + interval '90 days',
      site_access_token_use_count = 0,
      updated_at = now()
  where id_empresa = p_id_empresa and id = p_id_agendamento;

  update public.agendamentos_servicos
  set id_funcionario = p_id_funcionario, inicio = p_inicio, fim = v_fim,
      status = 'reservado', updated_at = now()
  where id_empresa = v_item.id_empresa and id = v_item.id;

  update public.tokens_links_agendamento set revogado_em = now()
  where id_empresa = p_id_empresa and id_agendamento = p_id_agendamento
    and revogado_em is null;
  perform private.enfileirar_mensagem_agendamento(
    p_id_empresa, p_id_agendamento, 'reagendamento', true
  );
  return v_novo_token;
end;
$$;

create or replace function private.reagendar_agendamento_site(
  p_token uuid,
  p_id_funcionario bigint,
  p_inicio timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_agendamento public.agendamentos%rowtype;
  v_novo_token uuid;
begin
  select * into v_agendamento from public.agendamentos a
  where a.site_access_token = p_token
    and coalesce(a.site_access_token_expires_at, now() - interval '1 second') > now()
  for update;
  if not found then raise exception 'O acesso a este agendamento expirou.'; end if;

  update public.agendamentos
  set site_access_token_use_count = site_access_token_use_count + 1
  where id_empresa = v_agendamento.id_empresa and id = v_agendamento.id;
  v_novo_token := private.reagendar_agendamento_core(
    v_agendamento.id_empresa, v_agendamento.id, p_id_funcionario, p_inicio,
    'link_cliente'
  );
  return private.obter_agendamento_site(v_novo_token);
end;
$$;

create or replace function private.alterar_agendamento_cliente_site(
  p_id_empresa bigint,
  p_id_agendamento bigint,
  p_acao text,
  p_motivo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_cliente_id bigint;
begin
  select c.id into v_cliente_id
  from public.agendamentos a
  join public.clientes c on c.id_empresa = a.id_empresa and c.id = a.id_cliente
  where a.id_empresa = p_id_empresa and a.id = p_id_agendamento
    and c.auth_user_id = auth.uid() and c.ativo
  for update of a;
  if not found then raise exception 'Agendamento nao encontrado para este cliente.'; end if;

  perform private.aplicar_acao_agendamento_cliente(
    p_id_empresa, p_id_agendamento, p_acao, p_motivo,
    'area_cliente', v_cliente_id, auth.uid()
  );
  return private.obter_area_cliente_site(p_id_empresa);
end;
$$;

create or replace function private.reagendar_agendamento_cliente_site(
  p_id_empresa bigint,
  p_id_agendamento bigint,
  p_id_funcionario bigint,
  p_inicio timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_cliente_id bigint;
begin
  select c.id into v_cliente_id
  from public.agendamentos a
  join public.clientes c on c.id_empresa = a.id_empresa and c.id = a.id_cliente
  where a.id_empresa = p_id_empresa and a.id = p_id_agendamento
    and c.auth_user_id = auth.uid() and c.ativo
  for update of a;
  if not found then raise exception 'Agendamento nao encontrado para este cliente.'; end if;

  perform private.reagendar_agendamento_core(
    p_id_empresa, p_id_agendamento, p_id_funcionario, p_inicio, 'area_cliente'
  );
  return private.obter_area_cliente_site(p_id_empresa);
end;
$$;

create or replace function public.reivindicar_estornos_agendamento(
  p_limite integer default 20,
  p_id_agendamento bigint default null
)
returns table (
  request_id bigint,
  company_id bigint,
  booking_id bigint,
  payment_id bigint,
  order_id text,
  amount numeric,
  idempotency_key uuid
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
  with escolhidas as (
    select r.id from public.solicitacoes_estorno_agendamento r
    where r.status in ('pendente', 'falhou')
      and r.proxima_tentativa_em <= now()
      and r.tentativas < 5
      and (p_id_agendamento is null or r.id_agendamento = p_id_agendamento)
    order by r.id
    limit least(greatest(coalesce(p_limite, 20), 1), 100)
    for update skip locked
  ), atualizadas as (
    update public.solicitacoes_estorno_agendamento r
    set status = 'processando', tentativas = r.tentativas + 1, updated_at = now()
    from escolhidas e where r.id = e.id
    returning r.*
  )
  select r.id, r.id_empresa, r.id_agendamento, r.id_pagamento,
    p.identificador_externo, r.valor, r.chave_idempotencia
  from atualizadas r
  join public.pagamentos p
    on p.id_empresa = r.id_empresa and p.id = r.id_pagamento;
end;
$$;

create or replace function public.concluir_estorno_agendamento(
  p_solicitacao_id bigint,
  p_provedor_status text,
  p_provedor_status_detalhe text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_solicitacao public.solicitacoes_estorno_agendamento%rowtype;
begin
  select * into v_solicitacao
  from public.solicitacoes_estorno_agendamento r
  where r.id = p_solicitacao_id for update;
  if not found then raise exception 'Solicitacao de estorno nao encontrada.'; end if;
  if v_solicitacao.status = 'confirmado' then return; end if;
  if v_solicitacao.status <> 'processando' then
    raise exception 'Solicitacao de estorno nao esta em processamento.';
  end if;

  update public.solicitacoes_estorno_agendamento
  set status = 'confirmado', provedor_status = p_provedor_status,
      provedor_status_detalhe = p_provedor_status_detalhe,
      processado_em = now(), ultimo_erro = null, updated_at = now()
  where id = p_solicitacao_id;
  update public.pagamentos
  set status = 'estornado', estornado_em = coalesce(estornado_em, now()),
      motivo_estorno = coalesce(motivo_estorno, v_solicitacao.motivo), updated_at = now()
  where id_empresa = v_solicitacao.id_empresa and id = v_solicitacao.id_pagamento;
  update public.agendamentos
  set sinal_status = 'estornado', pagamento_status = 'estornado', updated_at = now()
  where id_empresa = v_solicitacao.id_empresa and id = v_solicitacao.id_agendamento;
end;
$$;

create or replace function public.falhar_estorno_agendamento(
  p_solicitacao_id bigint,
  p_erro text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.solicitacoes_estorno_agendamento
  set status = case when tentativas >= 5 then 'revisao_manual' else 'falhou' end,
      ultimo_erro = left(coalesce(p_erro, 'Falha desconhecida.'), 1000),
      proxima_tentativa_em = now() + make_interval(mins => least(60, power(2, tentativas)::integer)),
      updated_at = now()
  where id = p_solicitacao_id and status = 'processando';
end;
$$;

revoke all on function private.emitir_token_link_agendamento(bigint,bigint,text,interval)
  from public, anon, authenticated;
revoke all on function private.cancelar_mensagens_agendamento(bigint,bigint)
  from public, anon, authenticated;
revoke all on function private.enfileirar_mensagem_agendamento(bigint,bigint,text,boolean)
  from public, anon, authenticated;
revoke all on function private.aplicar_acao_agendamento_cliente(bigint,bigint,text,text,text,bigint,uuid)
  from public, anon, authenticated;
revoke all on function private.reagendar_agendamento_core(bigint,bigint,bigint,timestamptz,text)
  from public, anon, authenticated;
revoke all on function public.consumir_token_link_agendamento(text)
  from public, anon, authenticated;
revoke all on function public.reivindicar_estornos_agendamento(integer,bigint)
  from public, anon, authenticated;
revoke all on function public.concluir_estorno_agendamento(bigint,text,text)
  from public, anon, authenticated;
revoke all on function public.falhar_estorno_agendamento(bigint,text)
  from public, anon, authenticated;

grant execute on function public.consumir_token_link_agendamento(text) to service_role;
grant execute on function public.reivindicar_estornos_agendamento(integer,bigint) to service_role;
grant execute on function public.concluir_estorno_agendamento(bigint,text,text) to service_role;
grant execute on function public.falhar_estorno_agendamento(bigint,text) to service_role;

-- Os wrappers públicos existentes continuam com as mesmas assinaturas.
revoke all on function public.obter_agendamento_site(uuid) from public, anon, authenticated;
revoke all on function public.alterar_agendamento_site(uuid,text,text) from public, anon, authenticated;
revoke all on function public.reagendar_agendamento_site(uuid,bigint,timestamptz) from public, anon, authenticated;
grant execute on function public.obter_agendamento_site(uuid) to anon, authenticated;
grant execute on function public.alterar_agendamento_site(uuid,text,text) to anon, authenticated;
grant execute on function public.reagendar_agendamento_site(uuid,bigint,timestamptz) to anon, authenticated;

comment on table public.tokens_links_agendamento is
  'Tokens de links armazenados somente como SHA-256, com expiracao, limite de uso e revogacao.';
comment on table public.solicitacoes_estorno_agendamento is
  'Outbox idempotente de estornos decididos pela politica de cancelamento.';
