-- Tabela isolada para estudos de integracao Supabase + n8n.
-- O service_role usado pelo n8n ignora RLS; anon e authenticated permanecem sem acesso.

create table public.games (
  id bigint generated by default as identity primary key,
  codigo uuid not null default gen_random_uuid(),
  nome text not null unique,
  genero text not null default 'Indefinido',
  plataforma text not null default 'PC',
  preco numeric(10,2) not null default 0 check (preco >= 0),
  nota numeric(3,1) not null default 0 check (nota between 0 and 10),
  ano_lancamento smallint not null default 2026 check (ano_lancamento between 1970 and 2100),
  multiplayer boolean not null default false,
  em_estoque boolean not null default true,
  quantidade integer not null default 0 check (quantidade >= 0),
  descricao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint games_codigo_unique unique (codigo)
);
alter table public.games enable row level security;
revoke all on table public.games from public, anon, authenticated;
revoke all on sequence public.games_id_seq from public, anon, authenticated;
grant all on table public.games to service_role;
grant usage, select on sequence public.games_id_seq to service_role;
insert into public.games (
  nome, genero, plataforma, preco, nota, ano_lancamento,
  multiplayer, em_estoque, quantidade, descricao
)
values
  ('Nebula Raiders', 'Acao', 'PC', 79.90, 8.7, 2024, true, true, 18, 'Exploracao espacial cooperativa.'),
  ('Vale dos Dragoes', 'RPG', 'PlayStation 5', 249.90, 9.1, 2025, false, true, 7, 'RPG de fantasia com escolhas que alteram a historia.'),
  ('Turbo Horizon', 'Corrida', 'Xbox Series X', 189.50, 8.3, 2023, true, true, 12, 'Campeonato de carros em cidades futuristas.'),
  ('Pixel Fazenda', 'Simulacao', 'Nintendo Switch', 59.90, 7.9, 2022, true, false, 0, 'Fazenda relaxante com construcao e comercio.'),
  ('Codigo Fantasma', 'Suspense', 'PC', 39.99, 8.5, 2026, false, true, 25, 'Investigacao digital em uma cidade controlada por IA.'),
  ('Arena dos Titas', 'Luta', 'Multiplataforma', 119.90, 7.6, 2024, true, true, 30, 'Batalhas competitivas com herois de diferentes eras.'),
  ('Ilha Perdida', 'Aventura', 'PlayStation 4', 89.00, 8.0, 2021, false, true, 4, 'Sobrevivencia e exploracao em uma ilha misteriosa.'),
  ('Reino de Cinzas', 'Estrategia', 'PC', 149.90, 9.3, 2025, true, true, 9, 'Construa um reino e dispute territorios.'),
  ('Gol de Rua 26', 'Esportes', 'Xbox Series S', 199.90, 7.4, 2026, true, false, 0, 'Futebol de rua com equipes personalizaveis.'),
  ('Mini Exploradores', 'Familia', 'Mobile', 0.00, 8.8, 2023, true, true, 999, 'Desafios educativos para jogar em familia.');
comment on table public.games is
  'Dados ficticios e isolados para exercicios de automacao com n8n.';
