-- Fase 12 - Administração
-- Configurações da empresa, convites, permissões por usuário,
-- integrações seguras e consultas de auditoria.

create table if not exists public.configuracoes_empresas (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null unique
    references public.empresas(id) on delete cascade,
  tema_preferido text not null default 'sistema'
    check (tema_preferido in ('sistema', 'claro', 'escuro')),
  cor_primaria text not null default '#226FE7'
    check (cor_primaria ~ '^#[0-9A-Fa-f]{6}$'),
  cor_destaque text not null default '#10B981'
    check (cor_destaque ~ '^#[0-9A-Fa-f]{6}$'),
  raio_interface text not null default 'medio'
    check (raio_interface in ('discreto', 'medio', 'arredondado')),
  densidade_interface text not null default 'confortavel'
    check (densidade_interface in ('compacta', 'confortavel')),
  logo_url text,
  idioma text not null default 'pt-BR',
  moeda text not null default 'BRL'
    check (moeda ~ '^[A-Z]{3}$'),
  semana_inicia smallint not null default 0
    check (semana_inicia between 0 and 6),
  duracao_slot_minutos smallint not null default 30
    check (duracao_slot_minutos in (10, 15, 20, 30, 45, 60)),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
create table if not exists public.convites_empresa (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null
    references public.empresas(id) on delete cascade,
  email text not null,
  tipo public.tipos_usuarios not null,
  status text not null default 'pendente'
    check (status in ('pendente', 'aceito', 'cancelado', 'expirado')),
  criado_por uuid references auth.users(id) on delete set null,
  aceito_por uuid references auth.users(id) on delete set null,
  expires_at timestamptz not null default (now() + interval '7 days'),
  aceito_em timestamptz,
  cancelado_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint convites_empresa_email_valido
    check (email = lower(btrim(email)) and position('@' in email) > 1)
);
create unique index if not exists convites_empresa_pendente_unique
  on public.convites_empresa (id_empresa, lower(email))
  where status = 'pendente';
create index if not exists convites_empresa_empresa_status_idx
  on public.convites_empresa (id_empresa, status, created_at desc);
create table if not exists public.permissoes_usuarios (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  usuario_empresa_id bigint not null,
  modulo text not null
    check (modulo in (
      'dashboard', 'agendamentos', 'clientes', 'comandas', 'orcamentos',
      'funcionarios', 'servicos', 'produtos', 'fornecedores', 'financeiro',
      'comissoes', 'estoque', 'historico', 'configuracoes'
    )),
  permitido boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  atualizado_por uuid references auth.users(id) on delete set null,
  constraint permissoes_usuarios_vinculo_fkey
    foreign key (id_empresa, usuario_empresa_id)
    references public.usuarios_empresas(empresa_id, id)
    on delete cascade,
  constraint permissoes_usuarios_unique
    unique (id_empresa, usuario_empresa_id, modulo)
);
create index if not exists permissoes_usuarios_vinculo_idx
  on public.permissoes_usuarios (id_empresa, usuario_empresa_id);
alter table public.integracoes
  drop constraint if exists integracoes_empresa_tipo_provedor_unique;
alter table public.integracoes
  add constraint integracoes_empresa_tipo_provedor_unique
  unique (id_empresa, tipo, provedor);
alter table public.configuracoes_empresas enable row level security;
alter table public.convites_empresa enable row level security;
alter table public.permissoes_usuarios enable row level security;
drop policy if exists configuracoes_empresas_membros_leem
  on public.configuracoes_empresas;
create policy configuracoes_empresas_membros_leem
  on public.configuracoes_empresas
  for select to authenticated
  using (private.usuario_pertence_empresa(id_empresa));
drop policy if exists convites_empresa_gestao_le
  on public.convites_empresa;
create policy convites_empresa_gestao_le
  on public.convites_empresa
  for select to authenticated
  using (
    private.usuario_tem_tipo_empresa(
      id_empresa,
      array['dono', 'gerente']::public.tipos_usuarios[]
    )
  );
drop policy if exists permissoes_usuarios_leitura
  on public.permissoes_usuarios;
create policy permissoes_usuarios_leitura
  on public.permissoes_usuarios
  for select to authenticated
  using (
    exists (
      select 1
      from public.usuarios_empresas ue
      where ue.id = usuario_empresa_id
        and ue.empresa_id = id_empresa
        and ue.status = 'ativo'::public.status_usuario_empresa
        and (
          ue.user_id = (select auth.uid())
          or private.usuario_tem_tipo_empresa(
            id_empresa,
            array['dono', 'gerente']::public.tipos_usuarios[]
          )
        )
    )
  );
revoke insert, update, delete on public.configuracoes_empresas from authenticated;
revoke insert, update, delete on public.convites_empresa from authenticated;
revoke insert, update, delete on public.permissoes_usuarios from authenticated;
grant select on public.configuracoes_empresas to authenticated;
grant select on public.convites_empresa to authenticated;
grant select on public.permissoes_usuarios to authenticated;
create or replace function private.plano_tem_funcionalidade_empresa(
  p_id_empresa bigint,
  p_funcionalidade text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select pp.ativo
    from public.assinaturas a
    join public.planos p on p.id = a.id_plano and p.ativo
    join public.permissoes_planos pp
      on pp.plano_id = p.id
     and pp.funcionalidade = p_funcionalidade
    where a.id_empresa = p_id_empresa
      and a.status::text in ('ativa', 'teste')
      and (a.teste_finaliza_em is null or a.teste_finaliza_em > now())
      and (a.periodo_atual_fim is null or a.periodo_atual_fim > now())
    order by a.inicio desc, a.id desc
    limit 1
  ), false);
$$;
create or replace function private.plano_limite_funcionalidade_empresa(
  p_id_empresa bigint,
  p_funcionalidade text
)
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when permissao.ilimitado then null
    else coalesce(permissao.limite, 0)::bigint
  end
  from (
    select pp.ilimitado, pp.limite
    from public.assinaturas a
    join public.planos p on p.id = a.id_plano and p.ativo
    join public.permissoes_planos pp
      on pp.plano_id = p.id
     and pp.funcionalidade = p_funcionalidade
     and pp.ativo
    where a.id_empresa = p_id_empresa
      and a.status::text in ('ativa', 'teste')
      and (a.teste_finaliza_em is null or a.teste_finaliza_em > now())
      and (a.periodo_atual_fim is null or a.periodo_atual_fim > now())
    order by a.inicio desc, a.id desc
    limit 1
  ) permissao;
$$;
revoke all on function private.plano_tem_funcionalidade_empresa(bigint, text)
  from public, anon, authenticated;
revoke all on function private.plano_limite_funcionalidade_empresa(bigint, text)
  from public, anon, authenticated;
create or replace function public.aceitar_convites_pendentes()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text;
  v_confirmado timestamptz;
  v_convite record;
  v_total integer := 0;
begin
  if auth.uid() is null then
    return 0;
  end if;

  select lower(u.email), u.email_confirmed_at
    into v_email, v_confirmado
  from auth.users u
  where u.id = auth.uid();

  if v_email is null or v_confirmado is null then
    return 0;
  end if;

  update public.convites_empresa
     set status = 'expirado', updated_at = now()
   where status = 'pendente'
     and expires_at <= now();

  for v_convite in
    select ce.*
    from public.convites_empresa ce
    where ce.status = 'pendente'
      and ce.expires_at > now()
      and lower(ce.email) = v_email
    order by ce.created_at
    for update
  loop
    insert into public.usuarios_empresas (empresa_id, user_id, tipo, status)
    values (
      v_convite.id_empresa,
      auth.uid(),
      v_convite.tipo,
      'ativo'::public.status_usuario_empresa
    )
    on conflict (empresa_id, user_id) do update
      set tipo = excluded.tipo,
          status = 'ativo'::public.status_usuario_empresa;

    update public.convites_empresa
       set status = 'aceito',
           aceito_por = auth.uid(),
           aceito_em = now(),
           updated_at = now()
     where id = v_convite.id;

    v_total := v_total + 1;
  end loop;

  return v_total;
end;
$$;
create or replace function public.listar_usuarios_administracao(
  p_id_empresa bigint
)
returns table (
  id bigint,
  user_id uuid,
  nome text,
  email text,
  tipo public.tipos_usuarios,
  status public.status_usuario_empresa,
  created_at timestamptz,
  ultimo_acesso_em timestamptz,
  permissoes jsonb
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono', 'gerente']::public.tipos_usuarios[]
  ) then
    raise exception 'Você não possui permissão para consultar os usuários.';
  end if;

  return query
  select
    ue.id,
    ue.user_id,
    coalesce(
      nullif(btrim(u.raw_user_meta_data ->> 'full_name'), ''),
      split_part(u.email, '@', 1),
      'Usuário'
    ) as nome,
    u.email,
    ue.tipo,
    ue.status,
    ue.created_at,
    u.last_sign_in_at,
    coalesce(
      jsonb_agg(
        jsonb_build_object('modulo', pu.modulo, 'permitido', pu.permitido)
        order by pu.modulo
      ) filter (where pu.id is not null),
      '[]'::jsonb
    ) as permissoes
  from public.usuarios_empresas ue
  join auth.users u on u.id = ue.user_id
  left join public.permissoes_usuarios pu
    on pu.id_empresa = ue.empresa_id
   and pu.usuario_empresa_id = ue.id
  where ue.empresa_id = p_id_empresa
  group by ue.id, ue.user_id, u.raw_user_meta_data, u.email,
           ue.tipo, ue.status, ue.created_at, u.last_sign_in_at
  order by
    case ue.tipo::text
      when 'dono' then 1
      when 'gerente' then 2
      when 'recepcionista' then 3
      else 4
    end,
    nome;
end;
$$;
create or replace function public.criar_convite_empresa(
  p_id_empresa bigint,
  p_email text,
  p_tipo public.tipos_usuarios
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text := lower(btrim(p_email));
  v_user_id uuid;
  v_limite bigint;
  v_em_uso bigint;
  v_convite_id bigint;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono']::public.tipos_usuarios[]
  ) then
    raise exception 'Somente o administrador pode convidar usuários.';
  end if;

  if v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Informe um e-mail válido.';
  end if;

  if not private.plano_tem_funcionalidade_empresa(p_id_empresa, 'usuarios') then
    raise exception 'O plano atual não permite adicionar usuários.';
  end if;

  update public.convites_empresa
     set status = 'expirado', updated_at = now()
   where id_empresa = p_id_empresa
     and status = 'pendente'
     and expires_at <= now();

  v_limite := private.plano_limite_funcionalidade_empresa(
    p_id_empresa,
    'usuarios'
  );

  select
    (select count(*) from public.usuarios_empresas ue
      where ue.empresa_id = p_id_empresa
        and ue.status = 'ativo'::public.status_usuario_empresa)
    +
    (select count(*) from public.convites_empresa ce
      where ce.id_empresa = p_id_empresa
        and ce.status = 'pendente'
        and ce.expires_at > now())
    into v_em_uso;

  if v_limite is not null and v_em_uso >= v_limite then
    raise exception 'O limite de usuários do plano foi atingido.';
  end if;

  if exists (
    select 1
    from public.usuarios_empresas ue
    join auth.users u on u.id = ue.user_id
    where ue.empresa_id = p_id_empresa
      and lower(u.email) = v_email
      and ue.status = 'ativo'::public.status_usuario_empresa
  ) then
    raise exception 'Este usuário já possui acesso ativo à empresa.';
  end if;

  select u.id into v_user_id
  from auth.users u
  where lower(u.email) = v_email
    and u.email_confirmed_at is not null
  order by u.created_at
  limit 1;

  if v_user_id is not null then
    insert into public.usuarios_empresas (empresa_id, user_id, tipo, status)
    values (
      p_id_empresa,
      v_user_id,
      p_tipo,
      'ativo'::public.status_usuario_empresa
    )
    on conflict (empresa_id, user_id) do update
      set tipo = excluded.tipo,
          status = 'ativo'::public.status_usuario_empresa;

    return jsonb_build_object(
      'status', 'ativado',
      'mensagem', 'O usuário já possuía conta e recebeu acesso imediatamente.'
    );
  end if;

  update public.convites_empresa
     set tipo = p_tipo,
         expires_at = now() + interval '7 days',
         criado_por = auth.uid(),
         updated_at = now()
   where id_empresa = p_id_empresa
     and lower(email) = v_email
     and status = 'pendente'
  returning id into v_convite_id;

  if v_convite_id is null then
    insert into public.convites_empresa (
      id_empresa, email, tipo, criado_por
    ) values (
      p_id_empresa, v_email, p_tipo, auth.uid()
    ) returning id into v_convite_id;
  end if;

  return jsonb_build_object(
    'status', 'pendente',
    'convite_id', v_convite_id,
    'mensagem', 'Convite registrado. O acesso será ativado quando esse e-mail entrar no sistema.'
  );
end;
$$;
create or replace function public.cancelar_convite_empresa(
  p_id_empresa bigint,
  p_convite_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono']::public.tipos_usuarios[]
  ) then
    raise exception 'Somente o administrador pode cancelar convites.';
  end if;

  update public.convites_empresa
     set status = 'cancelado', cancelado_em = now(), updated_at = now()
   where id = p_convite_id
     and id_empresa = p_id_empresa
     and status = 'pendente';

  if not found then
    raise exception 'Convite pendente não encontrado.';
  end if;
end;
$$;
create or replace function public.atualizar_usuario_empresa_administracao(
  p_id_empresa bigint,
  p_usuario_empresa_id bigint,
  p_tipo public.tipos_usuarios,
  p_status public.status_usuario_empresa
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_limite bigint;
  v_ativos bigint;
  v_status_atual public.status_usuario_empresa;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono']::public.tipos_usuarios[]
  ) then
    raise exception 'Somente o administrador pode alterar usuários e cargos.';
  end if;

  select ue.status into v_status_atual
  from public.usuarios_empresas ue
  where ue.id = p_usuario_empresa_id
    and ue.empresa_id = p_id_empresa
  for update;

  if v_status_atual is null then
    raise exception 'Usuário da empresa não encontrado.';
  end if;

  if v_status_atual <> 'ativo'::public.status_usuario_empresa
     and p_status = 'ativo'::public.status_usuario_empresa then
    v_limite := private.plano_limite_funcionalidade_empresa(
      p_id_empresa,
      'usuarios'
    );

    select count(*) into v_ativos
    from public.usuarios_empresas ue
    where ue.empresa_id = p_id_empresa
      and ue.status = 'ativo'::public.status_usuario_empresa;

    if v_limite is not null and v_ativos >= v_limite then
      raise exception 'O limite de usuários do plano foi atingido.';
    end if;
  end if;

  update public.usuarios_empresas
     set tipo = p_tipo,
         status = p_status
   where id = p_usuario_empresa_id
     and empresa_id = p_id_empresa;
end;
$$;
create or replace function public.salvar_permissoes_usuario(
  p_id_empresa bigint,
  p_usuario_empresa_id bigint,
  p_permissoes jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_modulo text;
  v_permitido boolean;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono']::public.tipos_usuarios[]
  ) then
    raise exception 'Somente o administrador pode personalizar permissões.';
  end if;

  if not private.plano_tem_funcionalidade_empresa(
    p_id_empresa,
    'permissoes_personalizadas'
  ) then
    raise exception 'Permissões personalizadas não estão disponíveis no plano atual.';
  end if;

  if jsonb_typeof(p_permissoes) <> 'array' then
    raise exception 'A lista de permissões é inválida.';
  end if;

  if not exists (
    select 1 from public.usuarios_empresas ue
    where ue.id = p_usuario_empresa_id
      and ue.empresa_id = p_id_empresa
  ) then
    raise exception 'Usuário da empresa não encontrado.';
  end if;

  delete from public.permissoes_usuarios
   where id_empresa = p_id_empresa
     and usuario_empresa_id = p_usuario_empresa_id;

  for v_item in select value from jsonb_array_elements(p_permissoes)
  loop
    v_modulo := v_item ->> 'modulo';
    v_permitido := coalesce((v_item ->> 'permitido')::boolean, true);

    if v_modulo not in (
      'dashboard', 'agendamentos', 'clientes', 'comandas', 'orcamentos',
      'funcionarios', 'servicos', 'produtos', 'fornecedores', 'financeiro',
      'comissoes', 'estoque', 'historico', 'configuracoes'
    ) then
      raise exception 'Módulo de permissão inválido: %.', v_modulo;
    end if;

    insert into public.permissoes_usuarios (
      id_empresa, usuario_empresa_id, modulo, permitido, atualizado_por
    ) values (
      p_id_empresa, p_usuario_empresa_id, v_modulo, v_permitido, auth.uid()
    );
  end loop;
end;
$$;
create or replace function public.atualizar_empresa_administracao(
  p_id_empresa bigint,
  p_fantasia text,
  p_razao_social text,
  p_cnpj text,
  p_email text,
  p_contato1 text,
  p_contato2 text,
  p_fuso_horario text
)
returns public.empresas
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_empresa public.empresas;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono']::public.tipos_usuarios[]
  ) then
    raise exception 'Somente o administrador pode alterar os dados da empresa.';
  end if;

  if nullif(btrim(p_fantasia), '') is null then
    raise exception 'Informe o nome da empresa.';
  end if;

  update public.empresas
     set fantasia = btrim(p_fantasia),
         razao_social = nullif(btrim(p_razao_social), ''),
         cnpj = nullif(regexp_replace(coalesce(p_cnpj, ''), '\D', '', 'g'), ''),
         email = nullif(lower(btrim(p_email)), ''),
         contato1 = nullif(btrim(p_contato1), ''),
         contato2 = nullif(btrim(p_contato2), ''),
         fuso_horario = coalesce(nullif(btrim(p_fuso_horario), ''), 'America/Sao_Paulo')
   where id = p_id_empresa
  returning * into v_empresa;

  if v_empresa.id is null then
    raise exception 'Empresa não encontrada.';
  end if;

  return v_empresa;
end;
$$;
create or replace function public.salvar_configuracoes_empresa(
  p_id_empresa bigint,
  p_tema_preferido text,
  p_cor_primaria text,
  p_cor_destaque text,
  p_raio_interface text,
  p_densidade_interface text,
  p_logo_url text,
  p_idioma text,
  p_moeda text,
  p_semana_inicia smallint,
  p_duracao_slot_minutos smallint
)
returns public.configuracoes_empresas
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_config public.configuracoes_empresas;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono']::public.tipos_usuarios[]
  ) then
    raise exception 'Somente o administrador pode alterar as preferências da empresa.';
  end if;

  if p_logo_url is not null
     and btrim(p_logo_url) <> ''
     and btrim(p_logo_url) !~ '^https://[^[:space:]]+$' then
    raise exception 'A URL do logotipo precisa começar com https://.';
  end if;

  insert into public.configuracoes_empresas (
    id_empresa, tema_preferido, cor_primaria, cor_destaque,
    raio_interface, densidade_interface, logo_url, idioma, moeda,
    semana_inicia, duracao_slot_minutos, updated_by
  ) values (
    p_id_empresa, p_tema_preferido, upper(p_cor_primaria), upper(p_cor_destaque),
    p_raio_interface, p_densidade_interface,
    nullif(btrim(p_logo_url), ''), p_idioma, upper(p_moeda),
    p_semana_inicia, p_duracao_slot_minutos, auth.uid()
  )
  on conflict (id_empresa) do update set
    tema_preferido = excluded.tema_preferido,
    cor_primaria = excluded.cor_primaria,
    cor_destaque = excluded.cor_destaque,
    raio_interface = excluded.raio_interface,
    densidade_interface = excluded.densidade_interface,
    logo_url = excluded.logo_url,
    idioma = excluded.idioma,
    moeda = excluded.moeda,
    semana_inicia = excluded.semana_inicia,
    duracao_slot_minutos = excluded.duracao_slot_minutos,
    updated_at = now(),
    updated_by = auth.uid()
  returning * into v_config;

  return v_config;
end;
$$;
create or replace function public.salvar_integracao_administracao(
  p_id_empresa bigint,
  p_tipo text,
  p_provedor text,
  p_configuracoes jsonb,
  p_status text default 'configurando'
)
returns public.integracoes
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_integracao public.integracoes;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono', 'gerente']::public.tipos_usuarios[]
  ) then
    raise exception 'Você não possui permissão para configurar integrações.';
  end if;

  if (p_tipo, p_provedor) not in (
    ('whatsapp', 'meta_cloud'),
    ('calendario', 'google_calendar'),
    ('email', 'resend'),
    ('webhook', 'webhook')
  ) then
    raise exception 'Tipo de integração não suportado.';
  end if;

  if jsonb_typeof(coalesce(p_configuracoes, '{}'::jsonb)) <> 'object' then
    raise exception 'As configurações da integração são inválidas.';
  end if;

  if coalesce(p_configuracoes, '{}'::jsonb) ?| array[
    'token', 'secret', 'password', 'senha', 'api_key', 'authorization'
  ] then
    raise exception 'Credenciais secretas devem ser salvas no servidor, nunca nesta configuração.';
  end if;

  if p_status not in ('configurando', 'inativa') then
    raise exception 'A ativação só pode ocorrer após validação segura das credenciais no servidor.';
  end if;

  insert into public.integracoes (
    id_empresa, tipo, provedor, configuracoes, status
  ) values (
    p_id_empresa, p_tipo, p_provedor,
    coalesce(p_configuracoes, '{}'::jsonb), p_status
  )
  on conflict (id_empresa, tipo, provedor) do update set
    configuracoes = excluded.configuracoes,
    status = excluded.status,
    ultimo_erro = null
  returning * into v_integracao;

  return v_integracao;
end;
$$;
create or replace function public.remover_integracao_administracao(
  p_id_empresa bigint,
  p_integracao_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono', 'gerente']::public.tipos_usuarios[]
  ) then
    raise exception 'Você não possui permissão para remover integrações.';
  end if;

  delete from public.integracoes
   where id = p_integracao_id
     and id_empresa = p_id_empresa;

  if not found then
    raise exception 'Integração não encontrada.';
  end if;
end;
$$;
create or replace function public.listar_auditoria_administracao(
  p_id_empresa bigint,
  p_busca text default null,
  p_acao text default null,
  p_tabela text default null,
  p_inicio timestamptz default null,
  p_fim timestamptz default null,
  p_pagina integer default 1,
  p_por_pagina integer default 20
)
returns table (
  id bigint,
  created_at timestamptz,
  acao text,
  tabela text,
  registro_id text,
  origem text,
  usuario_id uuid,
  usuario_nome text,
  usuario_email text,
  papel_execucao text,
  campos_alterados text[],
  dados_anteriores jsonb,
  dados_novos jsonb,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono', 'gerente']::public.tipos_usuarios[]
  ) then
    raise exception 'Você não possui permissão para consultar a auditoria.';
  end if;

  if not private.plano_tem_funcionalidade_empresa(p_id_empresa, 'auditoria') then
    raise exception 'A auditoria detalhada não está disponível no plano atual.';
  end if;

  return query
  select
    a.id,
    a.created_at,
    a.acao,
    a.tabela,
    a.registro_id,
    a.origem,
    a.usuario_id,
    coalesce(
      nullif(btrim(u.raw_user_meta_data ->> 'full_name'), ''),
      split_part(u.email, '@', 1),
      case when a.origem = 'sistema' then 'Sistema' else 'Usuário removido' end
    ) as usuario_nome,
    u.email as usuario_email,
    a.papel_execucao,
    a.campos_alterados,
    a.dados_anteriores,
    a.dados_novos,
    count(*) over() as total_count
  from public.auditorias a
  left join auth.users u on u.id = a.usuario_id
  where a.id_empresa = p_id_empresa
    and (
      nullif(btrim(p_busca), '') is null
      or a.tabela ilike '%' || btrim(p_busca) || '%'
      or a.registro_id ilike '%' || btrim(p_busca) || '%'
      or coalesce(u.email, '') ilike '%' || btrim(p_busca) || '%'
      or coalesce(u.raw_user_meta_data ->> 'full_name', '') ilike '%' || btrim(p_busca) || '%'
    )
    and (nullif(p_acao, '') is null or a.acao = p_acao)
    and (nullif(p_tabela, '') is null or a.tabela = p_tabela)
    and (p_inicio is null or a.created_at >= p_inicio)
    and (p_fim is null or a.created_at < p_fim)
  order by a.created_at desc, a.id desc
  limit least(greatest(p_por_pagina, 1), 100)
  offset (greatest(p_pagina, 1) - 1) * least(greatest(p_por_pagina, 1), 100);
end;
$$;
grant execute on function public.aceitar_convites_pendentes() to authenticated;
grant execute on function public.listar_usuarios_administracao(bigint) to authenticated;
grant execute on function public.criar_convite_empresa(bigint, text, public.tipos_usuarios) to authenticated;
grant execute on function public.cancelar_convite_empresa(bigint, bigint) to authenticated;
grant execute on function public.atualizar_usuario_empresa_administracao(bigint, bigint, public.tipos_usuarios, public.status_usuario_empresa) to authenticated;
grant execute on function public.salvar_permissoes_usuario(bigint, bigint, jsonb) to authenticated;
grant execute on function public.atualizar_empresa_administracao(bigint, text, text, text, text, text, text, text) to authenticated;
grant execute on function public.salvar_configuracoes_empresa(bigint, text, text, text, text, text, text, text, text, smallint, smallint) to authenticated;
grant execute on function public.salvar_integracao_administracao(bigint, text, text, jsonb, text) to authenticated;
grant execute on function public.remover_integracao_administracao(bigint, bigint) to authenticated;
grant execute on function public.listar_auditoria_administracao(bigint, text, text, text, timestamptz, timestamptz, integer, integer) to authenticated;
drop trigger if exists configuracoes_empresas_updated_at
  on public.configuracoes_empresas;
create trigger configuracoes_empresas_updated_at
before update on public.configuracoes_empresas
for each row execute function private.definir_updated_at();
drop trigger if exists convites_empresa_updated_at
  on public.convites_empresa;
create trigger convites_empresa_updated_at
before update on public.convites_empresa
for each row execute function private.definir_updated_at();
drop trigger if exists permissoes_usuarios_updated_at
  on public.permissoes_usuarios;
create trigger permissoes_usuarios_updated_at
before update on public.permissoes_usuarios
for each row execute function private.definir_updated_at();
drop trigger if exists configuracoes_empresas_auditar
  on public.configuracoes_empresas;
create trigger configuracoes_empresas_auditar
after insert or update or delete on public.configuracoes_empresas
for each row execute function private.registrar_auditoria();
drop trigger if exists convites_empresa_auditar
  on public.convites_empresa;
create trigger convites_empresa_auditar
after insert or update or delete on public.convites_empresa
for each row execute function private.registrar_auditoria();
drop trigger if exists permissoes_usuarios_auditar
  on public.permissoes_usuarios;
create trigger permissoes_usuarios_auditar
after insert or update or delete on public.permissoes_usuarios
for each row execute function private.registrar_auditoria();
comment on table public.configuracoes_empresas is
  'Preferências operacionais e visuais compartilhadas pela empresa.';
comment on table public.convites_empresa is
  'Convites sem credenciais; o acesso é ativado somente para o e-mail autenticado e confirmado.';
comment on table public.permissoes_usuarios is
  'Restrições adicionais de módulos por usuário. Não concede acesso além do cargo e do plano.';
comment on function public.salvar_integracao_administracao(bigint, text, text, jsonb, text) is
  'Salva apenas configurações públicas. Tokens e segredos devem ficar em backend/Vault.';
