-- Fase 13: fundacao operacional versionada para agenda publica multiempresa.
-- Mantem o modelo normalizado existente:
--   profissionais            -> public.funcionarios
--   profissionais_servicos   -> public.funcionarios_servicos
--   disponibilidade recorrente -> public.funcionarios_horarios
--   notificacoes             -> public.fila_mensagens (view publica abaixo)

create table if not exists public.unidades (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  nome text not null,
  codigo text not null,
  telefone text,
  email text,
  endereco text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  cep text,
  fuso_horario text not null default 'America/Sao_Paulo',
  principal boolean not null default false,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint unidades_empresa_fkey foreign key (id_empresa)
    references public.empresas(id) on delete cascade,
  constraint unidades_empresa_id_unique unique (id_empresa, id),
  constraint unidades_empresa_codigo_unique unique (id_empresa, codigo),
  constraint unidades_nome_check check (char_length(btrim(nome)) between 2 and 120),
  constraint unidades_codigo_check check (codigo ~ '^[a-z0-9][a-z0-9-]{1,59}$')
);

create unique index if not exists unidades_principal_por_empresa_unique
  on public.unidades (id_empresa)
  where principal and ativo;

create table if not exists public.horarios_funcionamento (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_unidade bigint not null,
  dia_semana smallint not null,
  hora_abertura time not null,
  hora_fechamento time not null,
  intervalo_inicio time,
  intervalo_fim time,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint horarios_funcionamento_unidade_fkey foreign key (id_empresa, id_unidade)
    references public.unidades(id_empresa, id) on delete cascade,
  constraint horarios_funcionamento_empresa_id_unique unique (id_empresa, id),
  constraint horarios_funcionamento_dia_unique unique (id_empresa, id_unidade, dia_semana),
  constraint horarios_funcionamento_dia_check check (dia_semana between 0 and 6),
  constraint horarios_funcionamento_periodo_check check (hora_fechamento > hora_abertura),
  constraint horarios_funcionamento_intervalo_check check (
    (intervalo_inicio is null and intervalo_fim is null)
    or (
      intervalo_inicio is not null
      and intervalo_fim is not null
      and intervalo_inicio > hora_abertura
      and intervalo_fim > intervalo_inicio
      and intervalo_fim < hora_fechamento
    )
  )
);

create table if not exists public.disponibilidades (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_unidade bigint not null,
  id_profissional bigint not null,
  inicio timestamptz not null,
  fim timestamptz not null,
  tipo text not null default 'indisponivel',
  origem text not null default 'manual',
  observacoes text,
  ativo boolean not null default true,
  id_bloqueio_agenda bigint,
  criado_por uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint disponibilidades_unidade_fkey foreign key (id_empresa, id_unidade)
    references public.unidades(id_empresa, id) on delete cascade,
  constraint disponibilidades_profissional_fkey foreign key (id_empresa, id_profissional)
    references public.funcionarios(id_empresa, id) on delete cascade,
  constraint disponibilidades_periodo_check check (fim > inicio),
  constraint disponibilidades_tipo_check check (tipo in ('disponivel', 'indisponivel'))
);

create index if not exists disponibilidades_consulta_idx
  on public.disponibilidades (id_empresa, id_unidade, id_profissional, inicio, fim)
  where ativo;

create table if not exists public.preferencias_lembrete (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_cliente bigint not null,
  whatsapp boolean not null default true,
  email boolean not null default true,
  sms boolean not null default false,
  push boolean not null default false,
  antecedencias_minutos integer[] not null default array[1440, 120],
  ativo boolean not null default true,
  origem text not null default 'painel',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint preferencias_lembrete_cliente_fkey foreign key (id_empresa, id_cliente)
    references public.clientes(id_empresa, id) on delete cascade,
  constraint preferencias_lembrete_cliente_unique unique (id_empresa, id_cliente),
  constraint preferencias_lembrete_antecedencias_check check (
    array_length(antecedencias_minutos, 1) is null
    or 0 < all(antecedencias_minutos)
  )
);

create table if not exists public.politicas_cancelamento (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_unidade bigint,
  antecedencia_cancelamento_minutos integer not null default 1440,
  antecedencia_reagendamento_minutos integer not null default 1440,
  antecedencia_agendamento_minutos integer not null default 120,
  janela_agendamento_dias integer not null default 60,
  tolerancia_atraso_minutos integer not null default 15,
  reter_sinal_fora_prazo boolean not null default true,
  multa_cancelamento_percentual numeric(5,2) not null default 0,
  texto_publico text,
  ativo boolean not null default true,
  vigente_desde date not null default current_date,
  vigente_ate date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint politicas_cancelamento_empresa_fkey foreign key (id_empresa)
    references public.empresas(id) on delete cascade,
  constraint politicas_cancelamento_unidade_fkey foreign key (id_empresa, id_unidade)
    references public.unidades(id_empresa, id) on delete cascade,
  constraint politicas_cancelamento_prazos_check check (
    antecedencia_cancelamento_minutos >= 0
    and antecedencia_reagendamento_minutos >= 0
    and antecedencia_agendamento_minutos >= 0
    and janela_agendamento_dias between 1 and 365
    and tolerancia_atraso_minutos between 0 and 180
    and multa_cancelamento_percentual between 0 and 100
  ),
  constraint politicas_cancelamento_vigencia_check check (
    vigente_ate is null or vigente_ate >= vigente_desde
  )
);

create unique index if not exists politicas_cancelamento_ativa_unique
  on public.politicas_cancelamento (id_empresa, coalesce(id_unidade, 0::bigint))
  where ativo and vigente_ate is null;

alter table public.agendamentos
  add column if not exists id_unidade bigint,
  add column if not exists valor_total numeric(12,2) not null default 0,
  add column if not exists pagamento_status text not null default 'nao_exigido',
  add column if not exists pagamento_externo_id text;

alter table public.bloqueios_agenda
  add column if not exists id_unidade bigint;

alter table public.pagamentos
  add column if not exists id_agendamento bigint,
  add column if not exists provedor text,
  add column if not exists identificador_externo text,
  add column if not exists chave_idempotencia text;

insert into public.unidades (
  id_empresa, nome, codigo, fuso_horario, principal, ativo
)
select
  e.id,
  'Unidade principal',
  'principal',
  coalesce(e.fuso_horario, 'America/Sao_Paulo'),
  true,
  true
from public.empresas e
where not exists (
  select 1 from public.unidades u where u.id_empresa = e.id
);

update public.agendamentos a
set id_unidade = u.id
from public.unidades u
where u.id_empresa = a.id_empresa
  and u.principal
  and u.ativo
  and a.id_unidade is null;

update public.bloqueios_agenda b
set id_unidade = u.id
from public.unidades u
where u.id_empresa = b.id_empresa
  and u.principal
  and u.ativo
  and b.id_unidade is null;

alter table public.agendamentos
  alter column id_unidade set not null;

alter table public.agendamentos
  add constraint agendamentos_unidade_empresa_fkey
  foreign key (id_empresa, id_unidade)
  references public.unidades(id_empresa, id);

alter table public.agendamentos
  add constraint agendamentos_pagamento_status_check
  check (pagamento_status in ('nao_exigido', 'pendente', 'processando', 'pago', 'falhou', 'estornado', 'cancelado'));

alter table public.bloqueios_agenda
  add constraint bloqueios_agenda_unidade_fkey
  foreign key (id_empresa, id_unidade)
  references public.unidades(id_empresa, id);

alter table public.disponibilidades
  add constraint disponibilidades_bloqueio_fkey
  foreign key (id_empresa, id_bloqueio_agenda)
  references public.bloqueios_agenda(id_empresa, id);

alter table public.pagamentos
  add constraint pagamentos_agendamento_fkey
  foreign key (id_empresa, id_agendamento)
  references public.agendamentos(id_empresa, id);

create unique index if not exists pagamentos_identificador_externo_unique
  on public.pagamentos (id_empresa, provedor, identificador_externo)
  where identificador_externo is not null;

create unique index if not exists pagamentos_chave_idempotencia_unique
  on public.pagamentos (id_empresa, chave_idempotencia)
  where chave_idempotencia is not null;

insert into public.horarios_funcionamento (
  id_empresa, id_unidade, dia_semana, hora_abertura, hora_fechamento,
  intervalo_inicio, intervalo_fim, ativo
)
select
  h.id_empresa,
  u.id,
  h.dia_semana,
  min(h.hora_inicio),
  max(h.hora_fim),
  min(h.intervalo_inicio) filter (where h.intervalo_inicio is not null),
  max(h.intervalo_fim) filter (where h.intervalo_fim is not null),
  true
from public.funcionarios_horarios h
join public.unidades u
  on u.id_empresa = h.id_empresa and u.principal and u.ativo
where h.ativo
group by h.id_empresa, u.id, h.dia_semana
on conflict (id_empresa, id_unidade, dia_semana) do nothing;

insert into public.politicas_cancelamento (
  id_empresa, id_unidade, antecedencia_cancelamento_minutos,
  antecedencia_reagendamento_minutos, antecedencia_agendamento_minutos,
  janela_agendamento_dias, tolerancia_atraso_minutos,
  reter_sinal_fora_prazo, multa_cancelamento_percentual, texto_publico
)
select
  e.id,
  null,
  1440,
  1440,
  120,
  60,
  15,
  true,
  0,
  'Cancelamentos e reagendamentos online devem ser solicitados com pelo menos 24 horas de antecedência.'
from public.empresas e
where not exists (
  select 1
  from public.politicas_cancelamento p
  where p.id_empresa = e.id and p.id_unidade is null and p.ativo
);

update public.agendamentos a
set valor_total = coalesce((
      select coalesce(
        sum(item.preco) filter (where item.status <> 'cancelado'),
        sum(item.preco),
        0
      )
      from public.agendamentos_servicos item
      where item.id_empresa = a.id_empresa and item.id_agendamento = a.id
    ), 0),
    pagamento_status = case
      when a.sinal_status = 'pago' then 'pago'
      when a.sinal_status = 'pendente' then 'pendente'
      else 'nao_exigido'
    end;

create table if not exists public.historico_agendamentos (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_agendamento bigint not null,
  id_unidade bigint not null,
  acao text not null,
  status_anterior text,
  status_novo text,
  motivo text,
  origem text not null default 'sistema',
  alterado_por uuid,
  dados_anteriores jsonb,
  dados_novos jsonb,
  created_at timestamptz not null default now(),
  constraint historico_agendamentos_agendamento_fkey foreign key (id_empresa, id_agendamento)
    references public.agendamentos(id_empresa, id) on delete cascade,
  constraint historico_agendamentos_unidade_fkey foreign key (id_empresa, id_unidade)
    references public.unidades(id_empresa, id),
  constraint historico_agendamentos_acao_check check (
    acao in ('criado', 'atualizado', 'confirmado', 'reagendado', 'cancelado', 'pagamento_atualizado', 'importado')
  )
);

create index if not exists historico_agendamentos_consulta_idx
  on public.historico_agendamentos (id_empresa, id_agendamento, created_at desc);

insert into public.historico_agendamentos (
  id_empresa, id_agendamento, id_unidade, acao, status_novo,
  motivo, origem, dados_novos, created_at
)
select
  a.id_empresa, a.id, a.id_unidade, 'importado', a.status,
  'Estado inicial registrado pela migration da Fase 13.',
  'migration', to_jsonb(a), a.created_at
from public.agendamentos a
where not exists (
  select 1
  from public.historico_agendamentos h
  where h.id_empresa = a.id_empresa and h.id_agendamento = a.id
);

create or replace function private.preparar_agendamento_operacional()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.id_unidade is null then
    select u.id into new.id_unidade
    from public.unidades u
    where u.id_empresa = new.id_empresa and u.ativo
    order by u.principal desc, u.id
    limit 1;
  end if;

  if new.id_unidade is null then
    raise exception 'A empresa precisa de uma unidade ativa para receber agendamentos.';
  end if;

  if tg_op = 'INSERT' or new.sinal_status is distinct from old.sinal_status then
    new.pagamento_status := case
      when new.sinal_status = 'pago' then 'pago'
      when new.sinal_status = 'pendente' then 'pendente'
      else coalesce(new.pagamento_status, 'nao_exigido')
    end;
  end if;

  return new;
end;
$$;

drop trigger if exists agendamentos_preparar_operacional on public.agendamentos;
create trigger agendamentos_preparar_operacional
before insert or update of id_empresa, id_unidade, sinal_status
on public.agendamentos
for each row execute function private.preparar_agendamento_operacional();

create or replace function private.recalcular_total_agendamento()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id_empresa bigint;
  v_id_agendamento bigint;
begin
  if tg_op = 'DELETE' then
    v_id_empresa := old.id_empresa;
    v_id_agendamento := old.id_agendamento;
  else
    v_id_empresa := new.id_empresa;
    v_id_agendamento := new.id_agendamento;
  end if;

  update public.agendamentos a
  set valor_total = coalesce((
    select coalesce(
      sum(item.preco) filter (where item.status <> 'cancelado'),
      sum(item.preco),
      0
    )
    from public.agendamentos_servicos item
    where item.id_empresa = v_id_empresa
      and item.id_agendamento = v_id_agendamento
  ), 0)
  where a.id_empresa = v_id_empresa and a.id = v_id_agendamento;

  return coalesce(new, old);
end;
$$;

drop trigger if exists agendamentos_servicos_recalcular_total on public.agendamentos_servicos;
create trigger agendamentos_servicos_recalcular_total
after insert or delete or update of preco, status, id_agendamento
on public.agendamentos_servicos
for each row execute function private.recalcular_total_agendamento();

-- Uma indisponibilidade operacional também vira bloqueio da agenda canônica.
-- Assim, o RPC público de horários continua usando uma única fonte de conflito.
create or replace function private.sincronizar_disponibilidade_com_bloqueio()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id_bloqueio bigint;
begin
  if tg_op = 'DELETE' then
    if old.id_bloqueio_agenda is not null then
      update public.bloqueios_agenda
      set status = 'cancelado',
          cancelado_em = now(),
          cancelado_por = auth.uid(),
          motivo_cancelamento = 'Disponibilidade removida.',
          updated_at = now()
      where id_empresa = old.id_empresa
        and id = old.id_bloqueio_agenda
        and status = 'ativo';
    end if;
    return old;
  end if;

  if new.tipo = 'indisponivel' and new.ativo then
    if new.id_bloqueio_agenda is null then
      insert into public.bloqueios_agenda (
        id_empresa, id_unidade, id_funcionario, tipo, inicio, fim,
        dia_inteiro, motivo, status, criado_por
      ) values (
        new.id_empresa, new.id_unidade, new.id_profissional,
        'bloqueio', new.inicio, new.fim, false,
        coalesce(new.observacoes, 'Indisponibilidade do profissional.'),
        'ativo', coalesce(new.criado_por, auth.uid())
      )
      returning id into v_id_bloqueio;

      new.id_bloqueio_agenda := v_id_bloqueio;
    else
      update public.bloqueios_agenda
      set id_unidade = new.id_unidade,
          id_funcionario = new.id_profissional,
          inicio = new.inicio,
          fim = new.fim,
          motivo = coalesce(new.observacoes, 'Indisponibilidade do profissional.'),
          status = 'ativo',
          cancelado_em = null,
          cancelado_por = null,
          motivo_cancelamento = null,
          updated_at = now()
      where id_empresa = new.id_empresa
        and id = new.id_bloqueio_agenda;
    end if;
  elsif new.id_bloqueio_agenda is not null then
    update public.bloqueios_agenda
    set status = 'cancelado',
        cancelado_em = now(),
        cancelado_por = auth.uid(),
        motivo_cancelamento = 'Indisponibilidade desativada.',
        updated_at = now()
    where id_empresa = new.id_empresa
      and id = new.id_bloqueio_agenda
      and status = 'ativo';
  end if;

  return new;
end;
$$;

drop trigger if exists disponibilidades_sincronizar_bloqueio on public.disponibilidades;
create trigger disponibilidades_sincronizar_bloqueio
before insert or update of id_empresa, id_unidade, id_profissional,
  inicio, fim, tipo, observacoes, ativo
or delete on public.disponibilidades
for each row execute function private.sincronizar_disponibilidade_com_bloqueio();

create or replace function private.registrar_historico_agendamento()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_acao text;
begin
  if tg_op = 'INSERT' then
    v_acao := 'criado';
  elsif new.status is distinct from old.status then
    v_acao := case new.status
      when 'confirmado' then 'confirmado'
      when 'cancelado' then 'cancelado'
      else 'atualizado'
    end;
  elsif new.inicio is distinct from old.inicio or new.fim is distinct from old.fim then
    v_acao := 'reagendado';
  elsif new.pagamento_status is distinct from old.pagamento_status
     or new.pagamento_externo_id is distinct from old.pagamento_externo_id then
    v_acao := 'pagamento_atualizado';
  else
    v_acao := 'atualizado';
  end if;

  insert into public.historico_agendamentos (
    id_empresa, id_agendamento, id_unidade, acao,
    status_anterior, status_novo, motivo, origem,
    alterado_por, dados_anteriores, dados_novos
  ) values (
    new.id_empresa, new.id, new.id_unidade, v_acao,
    case when tg_op = 'UPDATE' then old.status end,
    new.status,
    case when v_acao = 'cancelado' then new.motivo_cancelamento end,
    case when new.site_booking_key is not null then 'site' else coalesce(new.origem, 'sistema') end,
    auth.uid(),
    case when tg_op = 'UPDATE' then to_jsonb(old) end,
    to_jsonb(new)
  );

  return new;
end;
$$;

drop trigger if exists agendamentos_registrar_historico on public.agendamentos;
create trigger agendamentos_registrar_historico
after insert or update of status, inicio, fim, id_cliente, id_unidade,
  sinal_status, sinal_valor, pagamento_status, pagamento_externo_id, valor_total
on public.agendamentos
for each row execute function private.registrar_historico_agendamento();

create or replace function private.sincronizar_preferencias_lembrete_site()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.site_notification_preferences is null then
    return new;
  end if;

  insert into public.preferencias_lembrete (
    id_empresa, id_cliente, whatsapp, email, sms, push,
    antecedencias_minutos, ativo, origem, updated_at
  ) values (
    new.id_empresa,
    new.id_cliente,
    coalesce((new.site_notification_preferences->>'whatsapp')::boolean, true),
    coalesce((new.site_notification_preferences->>'email')::boolean, true),
    false,
    false,
    array[1440, 120],
    true,
    'site',
    now()
  )
  on conflict (id_empresa, id_cliente) do update
  set whatsapp = excluded.whatsapp,
      email = excluded.email,
      ativo = true,
      origem = 'site',
      updated_at = now();

  return new;
end;
$$;

insert into public.preferencias_lembrete (
  id_empresa, id_cliente, whatsapp, email, sms, push,
  antecedencias_minutos, ativo, origem, updated_at
)
select distinct on (a.id_empresa, a.id_cliente)
  a.id_empresa,
  a.id_cliente,
  coalesce((a.site_notification_preferences->>'whatsapp')::boolean, true),
  coalesce((a.site_notification_preferences->>'email')::boolean, true),
  false,
  false,
  array[1440, 120],
  true,
  'site',
  a.updated_at
from public.agendamentos a
where a.site_notification_preferences is not null
order by a.id_empresa, a.id_cliente, a.updated_at desc
on conflict (id_empresa, id_cliente) do update
set whatsapp = excluded.whatsapp,
    email = excluded.email,
    ativo = excluded.ativo,
    origem = excluded.origem,
    updated_at = excluded.updated_at;

drop trigger if exists agendamentos_sincronizar_preferencias_site on public.agendamentos;
create trigger agendamentos_sincronizar_preferencias_site
after insert or update of site_notification_preferences
on public.agendamentos
for each row execute function private.sincronizar_preferencias_lembrete_site();

-- Nomes de dominio amigaveis sem duplicar dados canônicos.
create or replace view public.profissionais
with (security_invoker = true)
as
select f.*
from public.funcionarios f
where f.atende_clientes;

create or replace view public.profissionais_servicos
with (security_invoker = true)
as
select fs.*
from public.funcionarios_servicos fs;

create or replace view public.notificacoes
with (security_invoker = true)
as
select
  m.id,
  m.id_empresa,
  m.id_cliente,
  m.id_evento,
  m.canal,
  m.destinatario,
  m.assunto as titulo,
  m.conteudo,
  m.dados_template,
  m.status,
  m.prioridade,
  m.agendada_para,
  m.enviada_em,
  m.entregue_em,
  m.lida_em,
  m.cancelada_em,
  m.identificador_externo,
  m.tentativas,
  m.ultimo_erro,
  m.created_at,
  m.updated_at
from public.fila_mensagens m;

alter table public.unidades enable row level security;
alter table public.horarios_funcionamento enable row level security;
alter table public.disponibilidades enable row level security;
alter table public.preferencias_lembrete enable row level security;
alter table public.politicas_cancelamento enable row level security;
alter table public.historico_agendamentos enable row level security;

create policy unidades_membros_leem on public.unidades
for select to authenticated using (private.usuario_pertence_empresa(id_empresa));
create policy unidades_membros_gerenciam on public.unidades
for all to authenticated using (private.usuario_pertence_empresa(id_empresa))
with check (private.usuario_pertence_empresa(id_empresa));

create policy horarios_funcionamento_membros_leem on public.horarios_funcionamento
for select to authenticated using (private.usuario_pertence_empresa(id_empresa));
create policy horarios_funcionamento_membros_gerenciam on public.horarios_funcionamento
for all to authenticated using (private.usuario_pertence_empresa(id_empresa))
with check (private.usuario_pertence_empresa(id_empresa));

create policy disponibilidades_membros_leem on public.disponibilidades
for select to authenticated using (private.usuario_pertence_empresa(id_empresa));
create policy disponibilidades_membros_gerenciam on public.disponibilidades
for all to authenticated using (private.usuario_pertence_empresa(id_empresa))
with check (private.usuario_pertence_empresa(id_empresa));

create policy preferencias_lembrete_membros_leem on public.preferencias_lembrete
for select to authenticated using (private.usuario_pertence_empresa(id_empresa));
create policy preferencias_lembrete_membros_gerenciam on public.preferencias_lembrete
for all to authenticated using (private.usuario_pertence_empresa(id_empresa))
with check (private.usuario_pertence_empresa(id_empresa));

create policy politicas_cancelamento_membros_leem on public.politicas_cancelamento
for select to authenticated using (private.usuario_pertence_empresa(id_empresa));
create policy politicas_cancelamento_membros_gerenciam on public.politicas_cancelamento
for all to authenticated using (private.usuario_pertence_empresa(id_empresa))
with check (private.usuario_pertence_empresa(id_empresa));

create policy historico_agendamentos_membros_leem on public.historico_agendamentos
for select to authenticated using (private.usuario_pertence_empresa(id_empresa));

revoke all on public.unidades, public.horarios_funcionamento,
  public.disponibilidades, public.preferencias_lembrete,
  public.politicas_cancelamento, public.historico_agendamentos
from anon;

grant select, insert, update, delete on public.unidades,
  public.horarios_funcionamento, public.disponibilidades,
  public.preferencias_lembrete, public.politicas_cancelamento
to authenticated;

grant select on public.historico_agendamentos,
  public.profissionais, public.profissionais_servicos, public.notificacoes
to authenticated;

do $$
declare
  v_sequence regclass;
begin
  foreach v_sequence in array array[
    'public.unidades_id_seq'::regclass,
    'public.horarios_funcionamento_id_seq'::regclass,
    'public.disponibilidades_id_seq'::regclass,
    'public.preferencias_lembrete_id_seq'::regclass,
    'public.politicas_cancelamento_id_seq'::regclass,
    'public.historico_agendamentos_id_seq'::regclass
  ]
  loop
    execute format('grant usage, select on sequence %s to authenticated', v_sequence);
  end loop;
end;
$$;

comment on table public.unidades is 'Unidades físicas de cada empresa; todo agendamento pertence a uma unidade.';
comment on table public.horarios_funcionamento is 'Jornada pública da unidade, separada da jornada individual dos profissionais.';
comment on table public.disponibilidades is 'Exceções versionadas de disponibilidade por profissional e unidade.';
comment on table public.historico_agendamentos is 'Histórico imutável de criação, status, reagendamento, cancelamento e pagamento.';
comment on table public.preferencias_lembrete is 'Preferências persistentes de comunicação do cliente por empresa.';
comment on table public.politicas_cancelamento is 'Regras de antecedência, atraso, sinal e cancelamento por empresa ou unidade.';
