import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { getErrorMessage } from '../../../components_shared/feedback/error.utils'
import { cancelBlock, cancelEmployeeAbsence, createBlock, createEmployee, createEmployeeAbsence, getEmployeeSchedule, getEmployeeServices, getEmployeesMetrics, listBlocks, listEmployeeAbsences, listEmployees, saveEmployeeSchedule, saveEmployeeServices, toggleEmployeeStatus, updateEmployee } from '../api/funcionarios.api'
import type { AbsenceInput, BlockInput, EmployeeServiceInput, FuncionarioWriteInput, FuncionariosListParams, ScheduleDayValue, ToggleFuncionarioStatusVariables, UpdateFuncionarioVariables } from '../types/funcionarios.types'
import { employeeKeys } from './funcionarios.keys'

const showError = (error: unknown) => toast.error(getErrorMessage(error, 'Não foi possível concluir a operação.'))
export function useEmployees(params: FuncionariosListParams) { return useQuery({ queryKey: employeeKeys.list(params), queryFn: () => listEmployees(params), enabled: params.companyId > 0, placeholderData: keepPreviousData }) }
export function useEmployeesMetrics(companyId: number) { return useQuery({ queryKey: employeeKeys.metrics(companyId), queryFn: () => getEmployeesMetrics(companyId), enabled: companyId > 0 }) }
function useInvalidateEmployees(companyId: number) { const client = useQueryClient(); return () => client.invalidateQueries({ queryKey: employeeKeys.all(companyId) }) }
export function useCreateEmployee(companyId: number) { const invalidate = useInvalidateEmployees(companyId); return useMutation({ mutationFn: (input: FuncionarioWriteInput) => createEmployee(companyId, input), onSuccess: async () => { await invalidate(); toast.success('Funcionário cadastrado com sucesso.') }, onError: showError }) }
export function useUpdateEmployee(companyId: number) { const invalidate = useInvalidateEmployees(companyId); return useMutation({ mutationFn: ({ employeeId, input }: UpdateFuncionarioVariables) => updateEmployee(companyId, employeeId, input), onSuccess: async () => { await invalidate(); toast.success('Funcionário atualizado com sucesso.') }, onError: showError }) }
export function useToggleEmployeeStatus(companyId: number) { const invalidate = useInvalidateEmployees(companyId); return useMutation({ mutationFn: ({ employeeId, active }: ToggleFuncionarioStatusVariables) => toggleEmployeeStatus(companyId, employeeId, active), onSuccess: async (employee) => { await invalidate(); toast.success(employee.ativo ? 'Funcionário reativado.' : 'Funcionário desativado.') }, onError: showError }) }

export function useEmployeeSchedule(companyId: number, employeeId: number) { return useQuery({ queryKey: employeeKeys.schedule(companyId, employeeId), queryFn: () => getEmployeeSchedule(companyId, employeeId), enabled: companyId > 0 && employeeId > 0 }) }
export function useSaveEmployeeSchedule(companyId: number, employeeId: number) { const client = useQueryClient(); return useMutation({ mutationFn: (days: ScheduleDayValue[]) => saveEmployeeSchedule(companyId, employeeId, days), onSuccess: async () => { await client.invalidateQueries({ queryKey: employeeKeys.schedule(companyId, employeeId) }); toast.success('Jornada salva com sucesso.') }, onError: showError }) }
export function useEmployeeServices(companyId: number, employeeId: number) { return useQuery({ queryKey: employeeKeys.services(companyId, employeeId), queryFn: () => getEmployeeServices(companyId, employeeId), enabled: companyId > 0 && employeeId > 0 }) }
export function useSaveEmployeeServices(companyId: number, employeeId: number) { const client = useQueryClient(); return useMutation({ mutationFn: (input: EmployeeServiceInput[]) => saveEmployeeServices(companyId, employeeId, input), onSuccess: async () => { await client.invalidateQueries({ queryKey: employeeKeys.services(companyId, employeeId) }); toast.success('Serviços do funcionário atualizados.') }, onError: showError }) }
export function useEmployeeAbsences(companyId: number, employeeId: number) { return useQuery({ queryKey: employeeKeys.absences(companyId, employeeId), queryFn: () => listEmployeeAbsences(companyId, employeeId), enabled: companyId > 0 && employeeId > 0 }) }
export function useCreateEmployeeAbsence(companyId: number, employeeId: number) { const client = useQueryClient(); return useMutation({ mutationFn: (input: AbsenceInput) => createEmployeeAbsence(companyId, employeeId, input), onSuccess: async () => { await client.invalidateQueries({ queryKey: employeeKeys.absences(companyId, employeeId) }); toast.success('Ausência registrada.') }, onError: showError }) }
export function useCancelEmployeeAbsence(companyId: number, employeeId: number) { const client = useQueryClient(); return useMutation({ mutationFn: (absenceId: number) => cancelEmployeeAbsence(companyId, absenceId), onSuccess: async () => { await client.invalidateQueries({ queryKey: employeeKeys.absences(companyId, employeeId) }); toast.success('Ausência cancelada.') }, onError: showError }) }
export function useBlocks(companyId: number) { return useQuery({ queryKey: employeeKeys.blocks(companyId), queryFn: () => listBlocks(companyId), enabled: companyId > 0 }) }
export function useCreateBlock(companyId: number) { const client = useQueryClient(); return useMutation({ mutationFn: (input: BlockInput) => createBlock(companyId, input), onSuccess: async () => { await client.invalidateQueries({ queryKey: employeeKeys.blocks(companyId) }); toast.success('Bloqueio criado com sucesso.') }, onError: showError }) }
export function useCancelBlock(companyId: number) { const client = useQueryClient(); return useMutation({ mutationFn: ({ blockId, reason }: { blockId: number; reason: string }) => cancelBlock(companyId, blockId, reason), onSuccess: async () => { await client.invalidateQueries({ queryKey: employeeKeys.blocks(companyId) }); toast.success('Bloqueio cancelado.') }, onError: showError }) }
