import { Modal } from "../../../components_shared";
import type { CommissionPayment } from "../types/commission.types";
import { COMMISSION_PAYMENT_STATUS_LABELS, formatCommissionCurrency, formatCommissionDate, formatCommissionDateTime } from "../utils/commission.utils";

type Props = { payment: CommissionPayment; onClose: () => void; onReverse: () => void };
export function CommissionPaymentDetailsModal({ payment, onClose, onReverse }: Props) {
  return <Modal open onClose={onClose} title={`Pagamento de comissão #${payment.id}`} description={`${payment.funcionario?.nome ?? "Funcionário removido"} · ${formatCommissionDateTime(payment.pago_em)}`} size="lg" footer={<><button className="btn btn--secondary" type="button" onClick={onClose}>Fechar</button>{payment.status === "confirmado" && <button className="btn btn--danger" type="button" onClick={onReverse}>Estornar pagamento</button>}</>}>
    <div className="commission-payment-details"><div className="commission-details-metrics"><article><span>Total</span><strong>{formatCommissionCurrency(payment.valor_total)}</strong></article><article><span>Forma</span><strong>{payment.forma?.nome ?? "—"}</strong></article><article><span>Status</span><strong><span className="commission-status" data-status={payment.status}>{COMMISSION_PAYMENT_STATUS_LABELS[payment.status as keyof typeof COMMISSION_PAYMENT_STATUS_LABELS] ?? payment.status}</span></strong></article></div><dl><div><dt>Período</dt><dd>{formatCommissionDate(payment.periodo_inicio)} a {formatCommissionDate(payment.periodo_fim)}</dd></div><div><dt>Caixa</dt><dd>{payment.sessao?.caixa?.nome ?? "Sem movimentação física"}</dd></div></dl><section><h3>Lançamentos pagos</h3><div className="commission-paid-items">{payment.itens.map((item) => <article key={item.id}><div><strong>{item.lancamento?.descricao_snapshot ?? `Comissão #${item.id_lancamento_comissao}`}</strong><small>Competência {formatCommissionDate(item.lancamento?.competencia)}</small></div><strong>{formatCommissionCurrency(item.valor)}</strong></article>)}</div></section>{payment.observacoes && <div className="commission-detail-note"><strong>Observações</strong><p>{payment.observacoes}</p></div>}{payment.motivo_cancelamento && <div className="commission-detail-note commission-detail-note--danger"><strong>Motivo do estorno</strong><p>{payment.motivo_cancelamento}</p></div>}</div>
  </Modal>;
}
