-- Operacao especializada para beleza: receitas de insumos, comissao liquida,
-- fechamento semanal e contrato seguro para automacoes externas (n8n).

alter table public.comissoes_regras
  add column if not exists descontar_taxa_pagamento boolean not null default true,
  add column if not exists descontar_insumos boolean not null default true;

alter table public.lancamentos_comissao
  add column if not exists taxa_pagamento_rateada numeric(14,2) not null default 0,
  add column if not exists custo_insumos_rateado numeric(14,2) not null default 0,
  add column if not exists base_original numeric(14,2);

update public.lancamentos_comissao
set base_original = base_calculo
where base_original is null;

alter table public.lancamentos_comissao
  alter column base_original set not null;

alter table public.comandas
  add column if not exists taxa_pagamento_snapshot numeric(14,2) not null default 0,
  add column if not exists custo_insumos_snapshot numeric(14,2) not null default 0;

create table if not exists public.servicos_insumos (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_servico bigint not null,
  id_produto bigint not null,
  quantidade_padrao numeric(14,4) not null,
  descontar_comissao boolean not null default true,
  ativo boolean not null default true,
  criado_por uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint servicos_insumos_empresa_fkey foreign key (id_empresa)
    references public.empresas(id) on delete cascade,
  constraint servicos_insumos_servico_fkey foreign key (id_empresa, id_servico)
    references public.servicos(id_empresa, id) on delete cascade,
  constraint servicos_insumos_produto_fkey foreign key (id_empresa, id_produto)
    references public.produtos(id_empresa, id) on delete restrict,
  constraint servicos_insumos_quantidade_check check (quantidade_padrao > 0),
  constraint servicos_insumos_unique unique (id_empresa, id_servico, id_produto)
);

create table if not exists public.consumos_insumos_comanda (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_comanda bigint not null,
  id_comanda_item bigint not null,
  id_servico bigint not null,
  id_produto bigint not null,
  id_funcionario bigint,
  quantidade_sugerida numeric(14,4) not null default 0,
  quantidade_utilizada numeric(14,4) not null,
  custo_unitario_snapshot numeric(14,4) not null default 0,
  custo_total numeric(14,2) generated always as (
    round(quantidade_utilizada * custo_unitario_snapshot, 2)
  ) stored,
  descontar_comissao boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint consumos_insumos_empresa_fkey foreign key (id_empresa)
    references public.empresas(id) on delete cascade,
  constraint consumos_insumos_comanda_fkey foreign key (id_empresa, id_comanda)
    references public.comandas(id_empresa, id) on delete cascade,
  constraint consumos_insumos_item_fkey foreign key (id_empresa, id_comanda_item)
    references public.comandas_itens(id_empresa, id) on delete cascade,
  constraint consumos_insumos_servico_fkey foreign key (id_empresa, id_servico)
    references public.servicos(id_empresa, id) on delete restrict,
  constraint consumos_insumos_produto_fkey foreign key (id_empresa, id_produto)
    references public.produtos(id_empresa, id) on delete restrict,
  constraint consumos_insumos_funcionario_fkey foreign key (id_empresa, id_funcionario)
    references public.funcionarios(id_empresa, id) on delete set null,
  constraint consumos_insumos_quantidade_check check (
    quantidade_sugerida >= 0 and quantidade_utilizada > 0
  ),
  constraint consumos_insumos_unique unique (id_empresa, id_comanda_item, id_produto)
);

alter table public.movimentos_estoque
  add column if not exists id_consumo_insumo bigint;

alter table public.movimentos_estoque
  drop constraint if exists movimentos_estoque_consumo_insumo_fkey;
alter table public.movimentos_estoque
  add constraint movimentos_estoque_consumo_insumo_fkey
  foreign key (id_consumo_insumo)
  references public.consumos_insumos_comanda(id)
  on delete set null;

create unique index if not exists movimentos_estoque_consumo_unique
  on public.movimentos_estoque (id_consumo_insumo)
  where id_consumo_insumo is not null and tipo = 'saida_consumo';

create table if not exists public.templates_mensagens_empresa (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresas(id) on delete cascade,
  tipo text not null,
  canal text not null,
  assunto text,
  conteudo text not null,
  ativo boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint templates_mensagens_tipo_check check (tipo in (
    'confirmacao_agendamento', 'confirmacao_reenviada', 'lembrete_agendamento',
    'reagendamento', 'cancelamento', 'resposta_reagendamento'
  )),
  constraint templates_mensagens_canal_check check (canal in ('whatsapp', 'email')),
  constraint templates_mensagens_conteudo_check check (btrim(conteudo) <> ''),
  constraint templates_mensagens_unique unique (id_empresa, tipo, canal)
);

create table if not exists public.eventos_mensagens_recebidas (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresas(id) on delete cascade,
  identificador_externo text not null,
  canal text not null default 'whatsapp',
  remetente text not null,
  conteudo text not null,
  id_cliente bigint,
  id_agendamento bigint,
  acao text not null default 'ignorada',
  resposta jsonb not null default '{}'::jsonb,
  recebido_em timestamptz not null default now(),
  processado_em timestamptz,
  constraint eventos_mensagens_cliente_fkey foreign key (id_empresa, id_cliente)
    references public.clientes(id_empresa, id) on delete set null,
  constraint eventos_mensagens_agendamento_fkey foreign key (id_empresa, id_agendamento)
    references public.agendamentos(id_empresa, id) on delete set null,
  constraint eventos_mensagens_externo_unique unique (id_empresa, identificador_externo),
  constraint eventos_mensagens_canal_check check (canal = 'whatsapp'),
  constraint eventos_mensagens_acao_check check (acao in (
    'confirmada', 'reagendamento_solicitado', 'pagamento_pendente',
    'sem_agendamento', 'ignorada', 'duplicada', 'erro'
  ))
);

create table if not exists public.eventos_funil_agendamento (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresas(id) on delete cascade,
  sessao uuid not null,
  evento text not null,
  etapa smallint,
  id_servico bigint,
  id_funcionario bigint,
  created_at timestamptz not null default now(),
  constraint eventos_funil_evento_check check (evento in (
    'inicio', 'servico_selecionado', 'horario_selecionado', 'dados_iniciados',
    'reserva_criada', 'abandono'
  )),
  constraint eventos_funil_etapa_check check (etapa is null or etapa between 1 and 3)
);

create index if not exists servicos_insumos_servico_idx
  on public.servicos_insumos (id_empresa, id_servico) where ativo;
create index if not exists consumos_insumos_comanda_idx
  on public.consumos_insumos_comanda (id_empresa, id_comanda);
create index if not exists eventos_mensagens_recebidas_data_idx
  on public.eventos_mensagens_recebidas (id_empresa, recebido_em desc);
create index if not exists eventos_funil_empresa_data_idx
  on public.eventos_funil_agendamento (id_empresa, created_at desc);

alter table public.servicos_insumos enable row level security;
alter table public.consumos_insumos_comanda enable row level security;
alter table public.templates_mensagens_empresa enable row level security;
alter table public.eventos_mensagens_recebidas enable row level security;
alter table public.eventos_funil_agendamento enable row level security;

drop policy if exists servicos_insumos_equipe_le on public.servicos_insumos;
create policy servicos_insumos_equipe_le on public.servicos_insumos
for select to authenticated using (private.usuario_pertence_empresa(id_empresa));

drop policy if exists consumos_insumos_equipe_le on public.consumos_insumos_comanda;
create policy consumos_insumos_equipe_le on public.consumos_insumos_comanda
for select to authenticated using (private.usuario_pertence_empresa(id_empresa));

drop policy if exists templates_mensagens_equipe_le on public.templates_mensagens_empresa;
create policy templates_mensagens_equipe_le on public.templates_mensagens_empresa
for select to authenticated using (private.usuario_pertence_empresa(id_empresa));

drop policy if exists eventos_mensagens_gestao_le on public.eventos_mensagens_recebidas;
create policy eventos_mensagens_gestao_le on public.eventos_mensagens_recebidas
for select to authenticated using (
  private.usuario_tem_tipo_empresa(
    id_empresa,
    array['dono'::public.tipos_usuarios, 'gerente'::public.tipos_usuarios]
  )
);

revoke all on public.servicos_insumos, public.consumos_insumos_comanda,
  public.templates_mensagens_empresa, public.eventos_mensagens_recebidas,
  public.eventos_funil_agendamento from anon, authenticated;
grant select on public.servicos_insumos, public.consumos_insumos_comanda,
  public.templates_mensagens_empresa, public.eventos_mensagens_recebidas
  to authenticated;

create or replace function private.touch_beauty_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists servicos_insumos_touch on public.servicos_insumos;
create trigger servicos_insumos_touch before update on public.servicos_insumos
for each row execute function private.touch_beauty_updated_at();
drop trigger if exists consumos_insumos_touch on public.consumos_insumos_comanda;
create trigger consumos_insumos_touch before update on public.consumos_insumos_comanda
for each row execute function private.touch_beauty_updated_at();
drop trigger if exists templates_mensagens_touch on public.templates_mensagens_empresa;
create trigger templates_mensagens_touch before update on public.templates_mensagens_empresa
for each row execute function private.touch_beauty_updated_at();

create or replace function public.salvar_insumos_servico(
  p_id_empresa bigint,
  p_id_servico bigint,
  p_insumos jsonb
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_produto_id bigint;
  v_quantidade numeric;
  v_total integer := 0;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono'::public.tipos_usuarios, 'gerente'::public.tipos_usuarios]
  ) then
    raise exception 'Voce nao possui permissao para configurar insumos.';
  end if;
  if not exists (
    select 1 from public.servicos s
    where s.id_empresa = p_id_empresa and s.id = p_id_servico
  ) then
    raise exception 'Servico invalido ou pertencente a outra empresa.';
  end if;
  if jsonb_typeof(coalesce(p_insumos, '[]'::jsonb)) <> 'array' then
    raise exception 'A lista de insumos e invalida.';
  end if;

  delete from public.servicos_insumos
  where id_empresa = p_id_empresa and id_servico = p_id_servico;

  for v_item in select value from jsonb_array_elements(coalesce(p_insumos, '[]'::jsonb))
  loop
    v_produto_id := nullif(v_item->>'id_produto', '')::bigint;
    v_quantidade := nullif(v_item->>'quantidade', '')::numeric;
    if v_produto_id is null or coalesce(v_quantidade, 0) <= 0 then
      raise exception 'Informe produto e quantidade validos para cada insumo.';
    end if;
    if not exists (
      select 1 from public.produtos p
      where p.id_empresa = p_id_empresa and p.id = v_produto_id
        and p.ativo and p.controla_estoque
    ) then
      raise exception 'O produto % nao esta ativo ou nao controla estoque.', v_produto_id;
    end if;
    insert into public.servicos_insumos (
      id_empresa, id_servico, id_produto, quantidade_padrao,
      descontar_comissao, ativo, criado_por
    ) values (
      p_id_empresa, p_id_servico, v_produto_id, v_quantidade,
      coalesce((v_item->>'descontar_comissao')::boolean, true), true, auth.uid()
    );
    v_total := v_total + 1;
  end loop;
  return v_total;
end;
$$;

create or replace function public.salvar_regra_comissao_beauty(
  p_regra_id bigint,
  p_id_empresa bigint,
  p_id_funcionario bigint,
  p_tipo_item text,
  p_id_servico bigint,
  p_id_produto bigint,
  p_tipo_calculo text,
  p_percentual numeric,
  p_valor_fixo numeric,
  p_base_calculo text,
  p_momento_liberacao text,
  p_vigente_de date,
  p_vigente_ate date,
  p_prioridade integer,
  p_ativo boolean,
  p_descontar_taxa_pagamento boolean default true,
  p_descontar_insumos boolean default true
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare v_id bigint;
begin
  v_id := public.salvar_regra_comissao(
    p_regra_id, p_id_empresa, p_id_funcionario, p_tipo_item,
    p_id_servico, p_id_produto, p_tipo_calculo, p_percentual,
    p_valor_fixo, p_base_calculo, p_momento_liberacao,
    p_vigente_de, p_vigente_ate, p_prioridade, p_ativo
  );
  update public.comissoes_regras
  set descontar_taxa_pagamento = coalesce(p_descontar_taxa_pagamento, true),
      descontar_insumos = coalesce(p_descontar_insumos, true),
      updated_at = now()
  where id_empresa = p_id_empresa and id = v_id;
  return v_id;
end;
$$;

create or replace function private.movimentar_estoque_comanda()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare r record;
begin
  if new.status = 'fechada' and old.status is distinct from 'fechada' then
    for r in
      select ci.id, ci.id_empresa, ci.id_produto, ci.quantidade, ci.descricao_snapshot
      from public.comandas_itens ci
      where ci.id_comanda = new.id and ci.tipo_item = 'produto'
    loop
      insert into public.movimentos_estoque (
        id_empresa,id_produto,tipo,quantidade,estoque_antes,estoque_depois,
        descricao,status,origem,id_comanda_item,movimentado_em,criado_por
      ) values (
        r.id_empresa,r.id_produto,'saida_venda',r.quantidade,0,0,
        'Venda na comanda #' || new.id || ' - ' || r.descricao_snapshot,
        'ativo','comanda',r.id,now(),auth.uid()
      ) on conflict (id_comanda_item) where id_comanda_item is not null and tipo = 'saida_venda'
        do nothing;
    end loop;

    for r in
      select c.id, c.id_empresa, c.id_comanda_item, c.id_produto,
             c.quantidade_utilizada, p.nome
      from public.consumos_insumos_comanda c
      join public.produtos p on p.id_empresa = c.id_empresa and p.id = c.id_produto
      where c.id_empresa = new.id_empresa and c.id_comanda = new.id
    loop
      insert into public.movimentos_estoque (
        id_empresa,id_produto,tipo,quantidade,estoque_antes,estoque_depois,
        descricao,status,origem,id_comanda_item,id_consumo_insumo,
        movimentado_em,criado_por
      ) values (
        r.id_empresa,r.id_produto,'saida_consumo',r.quantidade_utilizada,0,0,
        'Consumo na comanda #' || new.id || ' - ' || r.nome,
        'ativo','comanda',r.id_comanda_item,r.id,now(),auth.uid()
      ) on conflict (id_consumo_insumo) where id_consumo_insumo is not null and tipo = 'saida_consumo'
        do nothing;
    end loop;
  elsif new.status = 'cancelada' and old.status is distinct from 'cancelada' then
    update public.movimentos_estoque me
    set status = 'estornado', motivo_estorno = 'Cancelamento da comanda', updated_at = now()
    where (
      me.id_comanda_item in (
        select ci.id from public.comandas_itens ci where ci.id_comanda = new.id
      )
      or me.id_consumo_insumo in (
        select c.id from public.consumos_insumos_comanda c where c.id_comanda = new.id
      )
    ) and me.tipo in ('saida_venda', 'saida_consumo') and me.status = 'ativo';
  end if;
  return new;
end;
$$;

create or replace function private.gerar_comissoes_comanda()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  i record;
  v_regra_id bigint;
  v_tipo text;
  v_percentual numeric;
  v_valor_fixo numeric;
  v_base_tipo text;
  v_momento text;
  v_descontar_taxa boolean;
  v_descontar_insumos boolean;
  v_base_original numeric;
  v_base numeric;
  v_comissao numeric;
  v_total_itens numeric;
  v_taxa_rateada numeric;
  v_insumos numeric;
begin
  if new.status = 'fechada' and old.status is distinct from 'fechada' then
    select coalesce(sum(greatest(ci.valor_total, 0)), 0)
    into v_total_itens
    from public.comandas_itens ci
    where ci.id_comanda = new.id
      and ci.id_funcionario is not null
      and ci.tipo_item in ('servico', 'produto');

    for i in
      select ci.* from public.comandas_itens ci
      where ci.id_comanda = new.id
        and ci.id_funcionario is not null
        and ci.tipo_item in ('servico', 'produto')
    loop
      v_regra_id := null; v_tipo := null; v_percentual := null; v_valor_fixo := null;
      v_base_tipo := null; v_momento := null;
      v_descontar_taxa := true; v_descontar_insumos := true;

      select r.id, r.tipo_calculo, r.percentual, r.valor_fixo,
             r.base_calculo, r.momento_liberacao,
             r.descontar_taxa_pagamento, r.descontar_insumos
      into v_regra_id, v_tipo, v_percentual, v_valor_fixo,
           v_base_tipo, v_momento, v_descontar_taxa, v_descontar_insumos
      from public.comissoes_regras r
      where r.id_empresa = new.id_empresa and r.ativo
        and r.vigente_de <= current_date
        and (r.vigente_ate is null or r.vigente_ate >= current_date)
        and (r.id_funcionario is null or r.id_funcionario = i.id_funcionario)
        and (
          r.tipo_item = 'todos'
          or (i.tipo_item = 'servico' and r.tipo_item = 'servico'
              and (r.id_servico is null or r.id_servico = i.id_servico))
          or (i.tipo_item = 'produto' and r.tipo_item = 'produto'
              and (r.id_produto is null or r.id_produto = i.id_produto))
        )
      order by (r.id_funcionario is not null) desc,
        (r.id_servico is not null or r.id_produto is not null) desc,
        r.prioridade desc, r.vigente_de desc, r.id desc
      limit 1;

      if v_regra_id is null and i.comissao_tipo_snapshot is not null
         and i.comissao_valor_snapshot is not null then
        v_tipo := case when i.comissao_tipo_snapshot = 'fixo' then 'valor_fixo'
                       else i.comissao_tipo_snapshot end;
        v_percentual := case when i.comissao_tipo_snapshot = 'percentual'
                             then i.comissao_valor_snapshot end;
        v_valor_fixo := case when i.comissao_tipo_snapshot = 'fixo'
                             then i.comissao_valor_snapshot end;
        v_base_tipo := 'liquido_desconto';
        v_momento := 'fechamento_comanda';
      end if;

      if v_tipo is not null then
        v_base_original := case when v_base_tipo = 'bruto'
          then i.quantidade * i.valor_unitario_snapshot
          else greatest(i.valor_total, 0)
        end;
        v_taxa_rateada := case
          when v_descontar_taxa and v_total_itens > 0
          then round(new.taxa_pagamento_snapshot * greatest(i.valor_total, 0) / v_total_itens, 2)
          else 0 end;
        select coalesce(sum(c.custo_total), 0)
        into v_insumos
        from public.consumos_insumos_comanda c
        where c.id_empresa = new.id_empresa and c.id_comanda_item = i.id
          and c.descontar_comissao and v_descontar_insumos;
        v_base := greatest(round(v_base_original - v_taxa_rateada - v_insumos, 2), 0);
        v_comissao := case when v_tipo = 'percentual'
          then round(v_base * v_percentual / 100, 2)
          else round(i.quantidade * v_valor_fixo, 2)
        end;

        if v_comissao > 0 then
          insert into public.lancamentos_comissao (
            id_empresa,id_funcionario,id_regra,id_comanda,id_comanda_item,
            tipo_origem,tipo_item,descricao_snapshot,desconto_rateado,
            base_original,taxa_pagamento_rateada,custo_insumos_rateado,
            base_calculo,tipo_calculo,percentual_snapshot,valor_fixo_snapshot,
            valor_comissao,valor_pago,status,competencia,momento_liberacao,liberada_em
          ) values (
            new.id_empresa,i.id_funcionario,v_regra_id,new.id,i.id,
            'comanda',i.tipo_item,i.descricao_snapshot,i.desconto,
            v_base_original,v_taxa_rateada,v_insumos,v_base,
            v_tipo,v_percentual,v_valor_fixo,v_comissao,0,
            case when v_momento = 'fechamento_comanda' then 'liberada' else 'prevista' end,
            current_date,v_momento,
            case when v_momento = 'fechamento_comanda' then now() end
          ) on conflict (id_comanda_item) do nothing;
        end if;
      end if;
    end loop;
  elsif new.status = 'cancelada' and old.status is distinct from 'cancelada' then
    update public.lancamentos_comissao
    set status = 'estornada', estornada_em = now(),
        motivo_estorno = 'Cancelamento da comanda', updated_at = now()
    where id_comanda = new.id and valor_pago = 0
      and status not in ('paga', 'parcial', 'estornada');
  end if;
  return new;
end;
$$;

create or replace function public.fechar_comanda_beauty(
  p_comanda_id bigint,
  p_id_empresa bigint,
  p_situacao_pagamento text,
  p_consumos jsonb default '[]'::jsonb,
  p_data_vencimento date default current_date,
  p_id_forma_pagamento bigint default null,
  p_id_sessao_caixa bigint default null,
  p_data_pagamento timestamptz default null,
  p_valor_pagamento numeric default null,
  p_referencia text default null,
  p_observacoes_pagamento text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_comanda_status text;
  v_total numeric;
  v_pagamento_base numeric;
  v_taxa_percentual numeric := 0;
  v_custo_insumos numeric := 0;
  v_falta record;
  v_resultado jsonb;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono'::public.tipos_usuarios, 'gerente'::public.tipos_usuarios,
          'recepcionista'::public.tipos_usuarios]
  ) then raise exception 'Voce nao possui permissao para fechar comandas.'; end if;

  select c.status, coalesce(c.valor_total, 0)
  into v_comanda_status, v_total
  from public.comandas c
  where c.id_empresa = p_id_empresa and c.id = p_comanda_id
  for update;
  if not found then raise exception 'Comanda nao encontrada.'; end if;
  if v_comanda_status <> 'aberta' then
    raise exception 'Apenas comandas abertas podem ser fechadas.';
  end if;
  if jsonb_typeof(coalesce(p_consumos, '[]'::jsonb)) <> 'array' then
    raise exception 'A lista de consumos e invalida.';
  end if;

  delete from public.consumos_insumos_comanda
  where id_empresa = p_id_empresa and id_comanda = p_comanda_id;

  for v_item in select value from jsonb_array_elements(coalesce(p_consumos, '[]'::jsonb))
  loop
    insert into public.consumos_insumos_comanda (
      id_empresa,id_comanda,id_comanda_item,id_servico,id_produto,id_funcionario,
      quantidade_sugerida,quantidade_utilizada,custo_unitario_snapshot,
      descontar_comissao
    )
    select p_id_empresa,p_comanda_id,ci.id,ci.id_servico,
      p.id,ci.id_funcionario,
      coalesce(si.quantidade_padrao, 0),
      nullif(v_item->>'quantidade', '')::numeric,
      coalesce(p.custo_medio, 0),
      coalesce((v_item->>'descontar_comissao')::boolean,
               si.descontar_comissao, true)
    from public.comandas_itens ci
    join public.produtos p
      on p.id_empresa = ci.id_empresa
     and p.id = nullif(v_item->>'id_produto', '')::bigint
     and p.ativo and p.controla_estoque
    left join public.servicos_insumos si
      on si.id_empresa = ci.id_empresa and si.id_servico = ci.id_servico
     and si.id_produto = p.id and si.ativo
    where ci.id_empresa = p_id_empresa and ci.id_comanda = p_comanda_id
      and ci.id = nullif(v_item->>'id_comanda_item', '')::bigint
      and ci.tipo_item = 'servico'
      and nullif(v_item->>'quantidade', '')::numeric > 0;
    if not found then
      raise exception 'Consumo invalido: confira servico, produto e quantidade.';
    end if;
  end loop;

  select p.nome, p.estoque_atual,
         coalesce(v.venda, 0) + coalesce(c.consumo, 0) necessario
  into v_falta
  from public.produtos p
  left join (
    select ci.id_produto, sum(ci.quantidade) venda
    from public.comandas_itens ci
    where ci.id_empresa = p_id_empresa and ci.id_comanda = p_comanda_id
      and ci.tipo_item = 'produto'
    group by ci.id_produto
  ) v on v.id_produto = p.id
  left join (
    select ci.id_produto, sum(ci.quantidade_utilizada) consumo
    from public.consumos_insumos_comanda ci
    where ci.id_empresa = p_id_empresa and ci.id_comanda = p_comanda_id
    group by ci.id_produto
  ) c on c.id_produto = p.id
  where p.id_empresa = p_id_empresa and p.controla_estoque
    and p.estoque_atual < coalesce(v.venda, 0) + coalesce(c.consumo, 0)
  limit 1;
  if found then
    raise exception 'Estoque insuficiente para %. Disponivel: %, necessario: %.',
      v_falta.nome, v_falta.estoque_atual, v_falta.necessario;
  end if;

  if p_situacao_pagamento <> 'a_receber' then
    select f.taxa_percentual into v_taxa_percentual
    from public.formas_pagamento f
    where f.id_empresa = p_id_empresa and f.id = p_id_forma_pagamento and f.ativo;
    if not found then raise exception 'Forma de pagamento invalida.'; end if;
  end if;
  v_pagamento_base := case
    when p_situacao_pagamento = 'pago' then v_total
    when p_situacao_pagamento = 'parcial' then coalesce(p_valor_pagamento, 0)
    else 0 end;
  select coalesce(sum(c.custo_total), 0) into v_custo_insumos
  from public.consumos_insumos_comanda c
  where c.id_empresa = p_id_empresa and c.id_comanda = p_comanda_id;

  update public.comandas
  set taxa_pagamento_snapshot = round(v_pagamento_base * coalesce(v_taxa_percentual, 0) / 100, 2),
      custo_insumos_snapshot = round(v_custo_insumos, 2), updated_at = now()
  where id_empresa = p_id_empresa and id = p_comanda_id;

  v_resultado := public.fechar_comanda_com_pagamento(
    p_comanda_id,p_id_empresa,p_situacao_pagamento,p_data_vencimento,
    p_id_forma_pagamento,p_id_sessao_caixa,p_data_pagamento,
    p_valor_pagamento,p_referencia,p_observacoes_pagamento
  );
  return v_resultado || jsonb_build_object(
    'taxa_pagamento', round(v_pagamento_base * coalesce(v_taxa_percentual, 0) / 100, 2),
    'custo_insumos', round(v_custo_insumos, 2)
  );
end;
$$;

create or replace function public.resumo_fechamento_semanal(
  p_id_empresa bigint,
  p_data_inicio date,
  p_data_fim date
)
returns table (
  id_funcionario bigint,
  funcionario_nome text,
  producao_bruta numeric,
  descontos numeric,
  taxas_pagamento numeric,
  custos_insumos numeric,
  base_comissao numeric,
  comissao_gerada numeric,
  ajustes numeric,
  valor_pago numeric,
  saldo_a_pagar numeric
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono'::public.tipos_usuarios, 'gerente'::public.tipos_usuarios]
  ) then raise exception 'Voce nao possui permissao para consultar o fechamento.'; end if;
  if p_data_inicio is null or p_data_fim is null or p_data_fim < p_data_inicio
     or p_data_fim - p_data_inicio > 62 then
    raise exception 'Periodo de fechamento invalido.';
  end if;

  return query
  select f.id, f.nome,
    round(coalesce(sum(l.base_original) filter (where l.tipo_origem = 'comanda'), 0), 2),
    round(coalesce(sum(l.desconto_rateado) filter (where l.tipo_origem = 'comanda'), 0), 2),
    round(coalesce(sum(l.taxa_pagamento_rateada) filter (where l.tipo_origem = 'comanda'), 0), 2),
    round(coalesce(sum(l.custo_insumos_rateado) filter (where l.tipo_origem = 'comanda'), 0), 2),
    round(coalesce(sum(l.base_calculo) filter (where l.tipo_origem = 'comanda'), 0), 2),
    round(coalesce(sum(l.valor_comissao) filter (where l.tipo_origem = 'comanda'), 0), 2),
    round(coalesce(sum(l.valor_comissao) filter (where l.tipo_origem = 'ajuste'), 0), 2),
    round(coalesce(sum(l.valor_pago), 0), 2),
    round(coalesce(sum(greatest(l.valor_comissao - l.valor_pago, 0))
      filter (where l.status in ('liberada', 'parcial')), 0), 2)
  from public.funcionarios f
  join public.lancamentos_comissao l
    on l.id_empresa = f.id_empresa and l.id_funcionario = f.id
   and l.competencia between p_data_inicio and p_data_fim
   and l.status <> 'estornada'
  where f.id_empresa = p_id_empresa
  group by f.id, f.nome
  order by f.nome;
end;
$$;

create or replace function public.registrar_fechamento_semanal(
  p_id_empresa bigint,
  p_data_inicio date,
  p_data_fim date,
  p_id_forma_pagamento bigint,
  p_id_sessao_caixa bigint default null,
  p_pago_em timestamptz default now(),
  p_observacoes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_funcionario record;
  v_itens jsonb;
  v_pagamento bigint;
  v_total numeric := 0;
  v_quantidade integer := 0;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa,
    array['dono'::public.tipos_usuarios, 'gerente'::public.tipos_usuarios]
  ) then raise exception 'Voce nao possui permissao para fechar comissoes.'; end if;
  if p_data_inicio is null or p_data_fim is null or p_data_fim < p_data_inicio
     or p_data_fim - p_data_inicio > 62 then raise exception 'Periodo invalido.'; end if;
  if not exists (
    select 1 from public.formas_pagamento f
    where f.id_empresa = p_id_empresa and f.id = p_id_forma_pagamento and f.ativo
  ) then raise exception 'Forma de pagamento invalida.'; end if;

  for v_funcionario in
    select l.id_funcionario,
      jsonb_agg(jsonb_build_object(
        'id_lancamento_comissao', l.id,
        'valor', round(l.valor_comissao - l.valor_pago, 2)
      ) order by l.id) itens,
      round(sum(l.valor_comissao - l.valor_pago), 2) total
    from public.lancamentos_comissao l
    where l.id_empresa = p_id_empresa
      and l.competencia between p_data_inicio and p_data_fim
      and l.status in ('liberada', 'parcial')
      and l.valor_comissao > l.valor_pago
    group by l.id_funcionario
  loop
    v_itens := v_funcionario.itens;
    v_pagamento := public.registrar_pagamento_comissao(
      p_id_empresa, v_funcionario.id_funcionario, p_id_forma_pagamento,
      p_id_sessao_caixa, coalesce(p_pago_em, now()), p_data_inicio, p_data_fim,
      concat_ws(E'\n', 'Fechamento semanal ' || p_data_inicio || ' a ' || p_data_fim,
        nullif(btrim(p_observacoes), '')), v_itens
    );
    v_total := v_total + v_funcionario.total;
    v_quantidade := v_quantidade + 1;
  end loop;
  if v_quantidade = 0 then raise exception 'Nao existem comissoes liberadas neste periodo.'; end if;
  return jsonb_build_object('profissionais', v_quantidade, 'valor_total', v_total);
end;
$$;

create or replace function public.n8n_reservar_mensagens(p_limite integer default 20)
returns table (
  id bigint, id_empresa bigint, canal text, destinatario text, assunto text,
  conteudo text, dados_template jsonb, tentativas integer, max_tentativas integer
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
  with escolhidas as (
    select m.id
    from public.fila_mensagens m
    where m.status in ('pendente', 'erro')
      and m.agendada_para <= now()
      and coalesce(m.proxima_tentativa_em, now()) <= now()
      and m.tentativas < m.max_tentativas
    order by m.prioridade desc, m.agendada_para, m.id
    for update skip locked
    limit least(greatest(coalesce(p_limite, 20), 1), 100)
  ), atualizadas as (
    update public.fila_mensagens m
    set status = 'processando', processamento_iniciado_em = now(),
        tentativas = tentativas + 1, updated_at = now()
    from escolhidas e where m.id = e.id
    returning m.*
  )
  select a.id,a.id_empresa,a.canal,a.destinatario,a.assunto,a.conteudo,
    a.dados_template,a.tentativas,a.max_tentativas
  from atualizadas a order by a.prioridade desc,a.agendada_para,a.id;
end;
$$;

create or replace function public.n8n_registrar_resultado_mensagem(
  p_id_mensagem bigint,
  p_status text,
  p_identificador_externo text default null,
  p_erro text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v_mensagem public.fila_mensagens%rowtype;
begin
  select * into v_mensagem from public.fila_mensagens m
  where m.id = p_id_mensagem for update;
  if not found then raise exception 'Mensagem nao encontrada.'; end if;
  if p_status not in ('enviada','entregue','lida','erro') then
    raise exception 'Status de mensagem invalido.';
  end if;
  if v_mensagem.status in ('entregue','lida') and p_status in ('enviada','erro') then
    return jsonb_build_object('id',v_mensagem.id,'status',v_mensagem.status,'duplicated',true);
  end if;
  update public.fila_mensagens
  set status = p_status,
      identificador_externo = coalesce(nullif(btrim(p_identificador_externo),''), identificador_externo),
      enviada_em = case when p_status in ('enviada','entregue','lida') then coalesce(enviada_em,now()) else enviada_em end,
      entregue_em = case when p_status in ('entregue','lida') then coalesce(entregue_em,now()) else entregue_em end,
      lida_em = case when p_status = 'lida' then coalesce(lida_em,now()) else lida_em end,
      ultimo_erro = case when p_status = 'erro' then left(coalesce(p_erro,'Erro nao informado.'),1000) else null end,
      proxima_tentativa_em = case when p_status = 'erro' and tentativas < max_tentativas
        then now() + make_interval(mins => least(60, power(2, greatest(tentativas,1))::integer)) else null end,
      processamento_iniciado_em = null, updated_at = now()
  where id = p_id_mensagem;
  return jsonb_build_object('id',p_id_mensagem,'status',p_status,'duplicated',false);
end;
$$;

create or replace function public.n8n_processar_resposta_whatsapp(
  p_id_empresa bigint,
  p_identificador_externo text,
  p_remetente text,
  p_conteudo text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existente public.eventos_mensagens_recebidas%rowtype;
  v_cliente public.clientes%rowtype;
  v_agendamento public.agendamentos%rowtype;
  v_texto text := upper(btrim(coalesce(p_conteudo,'')));
  v_acao text := 'ignorada';
  v_emitido jsonb;
  v_link text;
  v_resposta jsonb;
begin
  if nullif(btrim(p_identificador_externo),'') is null
     or nullif(regexp_replace(p_remetente,'[^0-9]','','g'),'') is null then
    raise exception 'Identificador e remetente sao obrigatorios.';
  end if;
  select * into v_existente from public.eventos_mensagens_recebidas e
  where e.id_empresa = p_id_empresa and e.identificador_externo = p_identificador_externo;
  if found then return v_existente.resposta || jsonb_build_object('duplicated',true); end if;

  select * into v_cliente from public.clientes c
  where c.id_empresa = p_id_empresa
    and right(regexp_replace(coalesce(c.telefone_e164,c.telefone_principal,''),'[^0-9]','','g'),11)
      = right(regexp_replace(p_remetente,'[^0-9]','','g'),11)
  order by c.updated_at desc,c.id desc limit 1;
  if not found then
    v_acao := 'sem_agendamento';
    v_resposta := jsonb_build_object('action',v_acao,'message','Cliente nao identificado.');
  else
    select * into v_agendamento from public.agendamentos a
    where a.id_empresa = p_id_empresa and a.id_cliente = v_cliente.id
      and a.inicio > now() and a.status in ('aguardando_confirmacao','aguardando_pagamento','confirmado')
    order by a.inicio limit 1 for update;
    if not found then
      v_acao := 'sem_agendamento';
      v_resposta := jsonb_build_object('action',v_acao,'message','Nenhum agendamento futuro encontrado.');
    elsif v_texto in ('1','SIM','CONFIRMAR','CONFIRMO') then
      if v_agendamento.sinal_status = 'pendente' then
        v_acao := 'pagamento_pendente';
        v_resposta := jsonb_build_object('action',v_acao,'bookingId',v_agendamento.id,
          'message','O sinal ainda precisa ser pago antes da confirmacao.');
      else
        perform private.aplicar_acao_agendamento_cliente(
          p_id_empresa,v_agendamento.id,'confirmar',null,'whatsapp_n8n',v_cliente.id,null
        );
        v_acao := 'confirmada';
        v_resposta := jsonb_build_object('action',v_acao,'bookingId',v_agendamento.id,
          'message','Presenca confirmada com sucesso.');
      end if;
    elsif v_texto in ('2','REMARCAR','REAGENDAR') then
      v_emitido := private.emitir_token_link_agendamento(
        p_id_empresa,v_agendamento.id,'gerenciar',interval '2 days'
      );
      v_link := '/confirmacao/acessar?token=' || (v_emitido->>'token');
      v_acao := 'reagendamento_solicitado';
      v_resposta := jsonb_build_object('action',v_acao,'bookingId',v_agendamento.id,
        'relativeLink',v_link,'expiresAt',v_emitido->>'expires_at',
        'message','Abra o link seguro para escolher um novo horario.');
    else
      v_resposta := jsonb_build_object('action',v_acao,'bookingId',v_agendamento.id,
        'message','Resposta nao reconhecida. Envie 1 para confirmar ou 2 para reagendar.');
    end if;
  end if;

  insert into public.eventos_mensagens_recebidas (
    id_empresa,identificador_externo,remetente,conteudo,id_cliente,id_agendamento,
    acao,resposta,processado_em
  ) values (
    p_id_empresa,btrim(p_identificador_externo),btrim(p_remetente),left(p_conteudo,500),
    v_cliente.id,v_agendamento.id,v_acao,v_resposta,now()
  );
  return v_resposta || jsonb_build_object('duplicated',false);
exception when unique_violation then
  select * into v_existente from public.eventos_mensagens_recebidas e
  where e.id_empresa = p_id_empresa and e.identificador_externo = p_identificador_externo;
  return v_existente.resposta || jsonb_build_object('duplicated',true);
end;
$$;

create or replace function public.registrar_evento_funil_agendamento(
  p_id_empresa bigint,
  p_sessao uuid,
  p_evento text,
  p_etapa smallint default null,
  p_id_servico bigint default null,
  p_id_funcionario bigint default null
)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.eventos_funil_agendamento(
    id_empresa,sessao,evento,etapa,id_servico,id_funcionario
  ) values (
    p_id_empresa,p_sessao,p_evento,p_etapa,p_id_servico,p_id_funcionario
  );
$$;

alter table public.agendamentos drop constraint if exists agendamentos_confirmacao_origem_check;
alter table public.agendamentos add constraint agendamentos_confirmacao_origem_check
check (confirmacao_origem is null or confirmacao_origem in (
  'link_cliente','area_cliente','pagamento_mercado_pago','equipe',
  'painel_administrativo','sistema','whatsapp_n8n'
));

revoke all on function public.salvar_insumos_servico(bigint,bigint,jsonb) from public;
revoke all on function public.salvar_regra_comissao_beauty(bigint,bigint,bigint,text,bigint,bigint,text,numeric,numeric,text,text,date,date,integer,boolean,boolean,boolean) from public;
revoke all on function public.fechar_comanda_beauty(bigint,bigint,text,jsonb,date,bigint,bigint,timestamptz,numeric,text,text) from public;
revoke all on function public.resumo_fechamento_semanal(bigint,date,date) from public;
revoke all on function public.registrar_fechamento_semanal(bigint,date,date,bigint,bigint,timestamptz,text) from public;
revoke all on function public.n8n_reservar_mensagens(integer) from public;
revoke all on function public.n8n_registrar_resultado_mensagem(bigint,text,text,text) from public;
revoke all on function public.n8n_processar_resposta_whatsapp(bigint,text,text,text) from public;
revoke all on function public.registrar_evento_funil_agendamento(bigint,uuid,text,smallint,bigint,bigint) from public;

grant execute on function public.salvar_insumos_servico(bigint,bigint,jsonb) to authenticated;
grant execute on function public.salvar_regra_comissao_beauty(bigint,bigint,bigint,text,bigint,bigint,text,numeric,numeric,text,text,date,date,integer,boolean,boolean,boolean) to authenticated;
grant execute on function public.fechar_comanda_beauty(bigint,bigint,text,jsonb,date,bigint,bigint,timestamptz,numeric,text,text) to authenticated;
grant execute on function public.resumo_fechamento_semanal(bigint,date,date) to authenticated;
grant execute on function public.registrar_fechamento_semanal(bigint,date,date,bigint,bigint,timestamptz,text) to authenticated;
grant execute on function public.n8n_reservar_mensagens(integer) to service_role;
grant execute on function public.n8n_registrar_resultado_mensagem(bigint,text,text,text) to service_role;
grant execute on function public.n8n_processar_resposta_whatsapp(bigint,text,text,text) to service_role;
grant execute on function public.registrar_evento_funil_agendamento(bigint,uuid,text,smallint,bigint,bigint) to service_role;

comment on table public.servicos_insumos is 'Receita padrao de insumos sugerida ao finalizar cada servico.';
comment on table public.consumos_insumos_comanda is 'Consumo real e custo congelado dos insumos usados no atendimento.';
comment on function public.fechar_comanda_beauty(bigint,bigint,text,jsonb,date,bigint,bigint,timestamptz,numeric,text,text)
  is 'Registra consumos, taxa, estoque, comissoes e financeiro em uma unica transacao.';
comment on function public.n8n_reservar_mensagens(integer)
  is 'Contrato service-role para o n8n reservar mensagens com SKIP LOCKED, sem duplicacao concorrente.';
