-- Fase 13: conteudo publico multiempresa resolvido por dominio ou slug.
-- Visitantes recebem somente o JSON publicado pela RPC; as tabelas continuam
-- protegidas por RLS e sem SELECT anonimo.

create table if not exists public.sites_publicos (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null unique references public.empresas(id) on delete cascade,
  id_unidade_principal bigint,
  slug text not null unique,
  publicado boolean not null default false,
  nome_publico text,
  titulo_hero text,
  destaque_hero text,
  descricao_hero text,
  titulo_sobre text,
  descricao_sobre text,
  imagem_hero_url text,
  imagem_compartilhamento_url text,
  instagram_url text,
  whatsapp text,
  email_publico text,
  texto_rodape text,
  titulo_seo text,
  descricao_seo text,
  palavras_chave text[] not null default '{}',
  diferenciais jsonb not null default '[]'::jsonb,
  perguntas_frequentes jsonb not null default '[]'::jsonb,
  mostrar_precos boolean not null default true,
  mostrar_profissionais boolean not null default true,
  mostrar_avaliacoes boolean not null default false,
  mostrar_endereco boolean not null default true,
  mostrar_horarios boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  atualizado_por uuid default auth.uid(),
  constraint sites_publicos_slug_formato_check
    check (slug = lower(slug) and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint sites_publicos_unidade_fkey
    foreign key (id_empresa, id_unidade_principal)
    references public.unidades(id_empresa, id) on delete set null,
  constraint sites_publicos_diferenciais_array_check
    check (jsonb_typeof(diferenciais) = 'array'),
  constraint sites_publicos_faq_array_check
    check (jsonb_typeof(perguntas_frequentes) = 'array')
);

create table if not exists public.sites_publicos_dominios (
  id bigint generated by default as identity primary key,
  id_site bigint not null references public.sites_publicos(id) on delete cascade,
  id_empresa bigint not null references public.empresas(id) on delete cascade,
  dominio text not null unique,
  principal boolean not null default false,
  created_at timestamptz not null default now(),
  constraint sites_publicos_dominios_formato_check
    check (
      dominio = lower(dominio)
      and dominio !~ '(^https?://|/|:)'
      and length(dominio) between 1 and 253
    ),
  constraint sites_publicos_dominios_empresa_site_unique
    unique (id_empresa, id_site, dominio)
);

create unique index if not exists sites_publicos_um_dominio_principal
  on public.sites_publicos_dominios (id_site)
  where principal;

create index if not exists sites_publicos_dominios_empresa_idx
  on public.sites_publicos_dominios (id_empresa);

create table if not exists public.avaliacoes (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null references public.empresas(id) on delete cascade,
  id_cliente bigint,
  id_agendamento bigint,
  nota smallint not null check (nota between 1 and 5),
  comentario text,
  nome_publico text,
  autorizado_publicacao boolean not null default false,
  status text not null default 'pendente'
    check (status in ('pendente', 'aprovada', 'rejeitada')),
  destaque boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint avaliacoes_cliente_fkey
    foreign key (id_empresa, id_cliente)
    references public.clientes(id_empresa, id) on delete set null,
  constraint avaliacoes_agendamento_fkey
    foreign key (id_empresa, id_agendamento)
    references public.agendamentos(id_empresa, id) on delete set null
);

create unique index if not exists avaliacoes_agendamento_unique
  on public.avaliacoes (id_empresa, id_agendamento)
  where id_agendamento is not null;

create index if not exists avaliacoes_publicadas_idx
  on public.avaliacoes (id_empresa, destaque desc, created_at desc)
  where status = 'aprovada' and autorizado_publicacao;

alter table public.sites_publicos enable row level security;
alter table public.sites_publicos_dominios enable row level security;
alter table public.avaliacoes enable row level security;

create policy sites_publicos_membros_leem
on public.sites_publicos for select to authenticated
using (private.usuario_pertence_empresa(id_empresa));

create policy sites_publicos_gestao_gerencia
on public.sites_publicos for all to authenticated
using (private.usuario_tem_tipo_empresa(
  id_empresa, array['dono', 'gerente']::public.tipos_usuarios[]
))
with check (private.usuario_tem_tipo_empresa(
  id_empresa, array['dono', 'gerente']::public.tipos_usuarios[]
));

create policy sites_publicos_dominios_membros_leem
on public.sites_publicos_dominios for select to authenticated
using (private.usuario_pertence_empresa(id_empresa));

create policy sites_publicos_dominios_gestao_gerencia
on public.sites_publicos_dominios for all to authenticated
using (private.usuario_tem_tipo_empresa(
  id_empresa, array['dono', 'gerente']::public.tipos_usuarios[]
))
with check (private.usuario_tem_tipo_empresa(
  id_empresa, array['dono', 'gerente']::public.tipos_usuarios[]
));

create policy avaliacoes_equipe_le
on public.avaliacoes for select to authenticated
using (private.usuario_pertence_empresa(id_empresa));

create policy avaliacoes_cliente_le_proprias
on public.avaliacoes for select to authenticated
using (private.usuario_eh_cliente(id_empresa, id_cliente));

create policy avaliacoes_cliente_cria_propria
on public.avaliacoes for insert to authenticated
with check (
  private.usuario_eh_cliente(id_empresa, id_cliente)
  and status = 'pendente'
  and not autorizado_publicacao
);

create policy avaliacoes_gestao_modera
on public.avaliacoes for update to authenticated
using (private.usuario_tem_tipo_empresa(
  id_empresa, array['dono', 'gerente']::public.tipos_usuarios[]
))
with check (private.usuario_tem_tipo_empresa(
  id_empresa, array['dono', 'gerente']::public.tipos_usuarios[]
));

create or replace function private.salvar_site_publico(
  p_id_empresa bigint,
  p_config jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_site public.sites_publicos%rowtype;
  v_slug text;
  v_dominio text;
  v_indice integer := 0;
begin
  if not private.usuario_tem_tipo_empresa(
    p_id_empresa, array['dono', 'gerente']::public.tipos_usuarios[]
  ) then
    raise exception 'Você não possui permissão para configurar o site público.';
  end if;

  v_slug := lower(btrim(coalesce(p_config->>'slug', '')));
  if v_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' then
    raise exception 'Use um slug com letras minúsculas, números e hífens.';
  end if;
  if jsonb_typeof(coalesce(p_config->'dominios', '[]'::jsonb)) <> 'array' then
    raise exception 'A lista de domínios é inválida.';
  end if;

  insert into public.sites_publicos (
    id_empresa, id_unidade_principal, slug, publicado, nome_publico,
    titulo_hero, destaque_hero, descricao_hero, titulo_sobre,
    descricao_sobre, imagem_hero_url, imagem_compartilhamento_url,
    instagram_url, whatsapp, email_publico, texto_rodape, titulo_seo,
    descricao_seo, palavras_chave, diferenciais, perguntas_frequentes,
    mostrar_precos, mostrar_profissionais, mostrar_avaliacoes,
    mostrar_endereco, mostrar_horarios, updated_at, atualizado_por
  ) values (
    p_id_empresa,
    nullif(p_config->>'id_unidade_principal', '')::bigint,
    v_slug,
    coalesce((p_config->>'publicado')::boolean, false),
    nullif(btrim(p_config->>'nome_publico'), ''),
    nullif(btrim(p_config->>'titulo_hero'), ''),
    nullif(btrim(p_config->>'destaque_hero'), ''),
    nullif(btrim(p_config->>'descricao_hero'), ''),
    nullif(btrim(p_config->>'titulo_sobre'), ''),
    nullif(btrim(p_config->>'descricao_sobre'), ''),
    nullif(btrim(p_config->>'imagem_hero_url'), ''),
    nullif(btrim(p_config->>'imagem_compartilhamento_url'), ''),
    nullif(btrim(p_config->>'instagram_url'), ''),
    nullif(btrim(p_config->>'whatsapp'), ''),
    nullif(btrim(p_config->>'email_publico'), ''),
    nullif(btrim(p_config->>'texto_rodape'), ''),
    nullif(btrim(p_config->>'titulo_seo'), ''),
    nullif(btrim(p_config->>'descricao_seo'), ''),
    coalesce(array(select jsonb_array_elements_text(coalesce(p_config->'palavras_chave', '[]'::jsonb))), '{}'),
    coalesce(p_config->'diferenciais', '[]'::jsonb),
    coalesce(p_config->'perguntas_frequentes', '[]'::jsonb),
    coalesce((p_config->>'mostrar_precos')::boolean, true),
    coalesce((p_config->>'mostrar_profissionais')::boolean, true),
    coalesce((p_config->>'mostrar_avaliacoes')::boolean, false),
    coalesce((p_config->>'mostrar_endereco')::boolean, true),
    coalesce((p_config->>'mostrar_horarios')::boolean, true),
    now(), auth.uid()
  )
  on conflict (id_empresa) do update set
    id_unidade_principal = excluded.id_unidade_principal,
    slug = excluded.slug,
    publicado = excluded.publicado,
    nome_publico = excluded.nome_publico,
    titulo_hero = excluded.titulo_hero,
    destaque_hero = excluded.destaque_hero,
    descricao_hero = excluded.descricao_hero,
    titulo_sobre = excluded.titulo_sobre,
    descricao_sobre = excluded.descricao_sobre,
    imagem_hero_url = excluded.imagem_hero_url,
    imagem_compartilhamento_url = excluded.imagem_compartilhamento_url,
    instagram_url = excluded.instagram_url,
    whatsapp = excluded.whatsapp,
    email_publico = excluded.email_publico,
    texto_rodape = excluded.texto_rodape,
    titulo_seo = excluded.titulo_seo,
    descricao_seo = excluded.descricao_seo,
    palavras_chave = excluded.palavras_chave,
    diferenciais = excluded.diferenciais,
    perguntas_frequentes = excluded.perguntas_frequentes,
    mostrar_precos = excluded.mostrar_precos,
    mostrar_profissionais = excluded.mostrar_profissionais,
    mostrar_avaliacoes = excluded.mostrar_avaliacoes,
    mostrar_endereco = excluded.mostrar_endereco,
    mostrar_horarios = excluded.mostrar_horarios,
    updated_at = now(),
    atualizado_por = auth.uid()
  returning * into v_site;

  delete from public.sites_publicos_dominios
  where id_site = v_site.id;

  for v_dominio in
    select distinct regexp_replace(
      split_part(regexp_replace(lower(btrim(value)), '^https?://', ''), '/', 1),
      ':[0-9]+$', ''
    )
    from jsonb_array_elements_text(coalesce(p_config->'dominios', '[]'::jsonb))
    where nullif(btrim(value), '') is not null
  loop
    if v_dominio !~ '^[a-z0-9.-]+$' then
      raise exception 'Domínio inválido: %', v_dominio;
    end if;
    insert into public.sites_publicos_dominios (
      id_site, id_empresa, dominio, principal
    ) values (v_site.id, p_id_empresa, v_dominio, v_indice = 0);
    v_indice := v_indice + 1;
  end loop;

  if v_indice = 0 then
    raise exception 'Informe pelo menos um domínio para publicar o site.';
  end if;

  return to_jsonb(v_site) || jsonb_build_object(
    'dominios', (
      select jsonb_agg(d.dominio order by d.principal desc, d.dominio)
      from public.sites_publicos_dominios d
      where d.id_site = v_site.id
    )
  );
end;
$$;

create or replace function public.salvar_site_publico(
  p_id_empresa bigint,
  p_config jsonb
)
returns jsonb
language sql
volatile
security invoker
set search_path = ''
as $$
  select private.salvar_site_publico(p_id_empresa, p_config);
$$;

create or replace function private.resolver_site_publico(
  p_dominio text default null,
  p_slug text default null
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with entrada as (
    select
      regexp_replace(
        split_part(regexp_replace(lower(btrim(coalesce(p_dominio, ''))), '^https?://', ''), '/', 1),
        ':[0-9]+$', ''
      ) as dominio,
      lower(btrim(coalesce(p_slug, ''))) as slug
  ), site_escolhido as (
    select sp.*
    from public.sites_publicos sp
    join public.empresas e on e.id = sp.id_empresa and e.status = 'ativo'
    cross join entrada x
    left join public.sites_publicos_dominios d on d.id_site = sp.id
    where sp.publicado
      and ((x.slug <> '' and sp.slug = x.slug) or (x.dominio <> '' and d.dominio = x.dominio))
    order by case when x.slug <> '' and sp.slug = x.slug then 0 else 1 end
    limit 1
  ), unidade_escolhida as (
    select u.*
    from site_escolhido sp
    join public.unidades u
      on u.id_empresa = sp.id_empresa
     and u.ativo
     and (u.id = sp.id_unidade_principal or (sp.id_unidade_principal is null and u.principal))
    order by (u.id = sp.id_unidade_principal) desc, u.principal desc, u.id
    limit 1
  )
  select jsonb_build_object(
    'site', jsonb_build_object(
      'id', sp.id,
      'slug', sp.slug,
      'dominio', (select d.dominio from public.sites_publicos_dominios d where d.id_site = sp.id order by d.principal desc, d.id limit 1),
      'nome_publico', coalesce(sp.nome_publico, e.fantasia),
      'titulo_hero', sp.titulo_hero,
      'destaque_hero', sp.destaque_hero,
      'descricao_hero', sp.descricao_hero,
      'titulo_sobre', sp.titulo_sobre,
      'descricao_sobre', sp.descricao_sobre,
      'imagem_hero_url', sp.imagem_hero_url,
      'imagem_compartilhamento_url', sp.imagem_compartilhamento_url,
      'instagram_url', sp.instagram_url,
      'whatsapp', coalesce(sp.whatsapp, ue.telefone),
      'email_publico', coalesce(sp.email_publico, ue.email),
      'texto_rodape', sp.texto_rodape,
      'titulo_seo', coalesce(sp.titulo_seo, sp.nome_publico, e.fantasia),
      'descricao_seo', coalesce(sp.descricao_seo, sp.descricao_hero),
      'palavras_chave', to_jsonb(sp.palavras_chave),
      'diferenciais', sp.diferenciais,
      'perguntas_frequentes', sp.perguntas_frequentes,
      'mostrar_precos', sp.mostrar_precos,
      'mostrar_profissionais', sp.mostrar_profissionais,
      'mostrar_avaliacoes', sp.mostrar_avaliacoes,
      'mostrar_endereco', sp.mostrar_endereco,
      'mostrar_horarios', sp.mostrar_horarios,
      'logo_url', ce.logo_url
    ),
    'empresa', jsonb_build_object(
      'id', e.id,
      'nome', e.fantasia,
      'fuso_horario', coalesce(e.fuso_horario, 'America/Sao_Paulo')
    ),
    'unidade', case when sp.mostrar_endereco and ue.id is not null then jsonb_build_object(
      'id', ue.id,
      'nome', ue.nome,
      'telefone', ue.telefone,
      'email', ue.email,
      'endereco', ue.endereco,
      'numero', ue.numero,
      'complemento', ue.complemento,
      'bairro', ue.bairro,
      'cidade', ue.cidade,
      'estado', ue.estado,
      'cep', ue.cep,
      'fuso_horario', ue.fuso_horario
    ) else null end,
    'horarios', case when sp.mostrar_horarios and ue.id is not null then coalesce((
      select jsonb_agg(jsonb_build_object(
        'dia_semana', h.dia_semana,
        'hora_abertura', h.hora_abertura,
        'hora_fechamento', h.hora_fechamento,
        'intervalo_inicio', h.intervalo_inicio,
        'intervalo_fim', h.intervalo_fim
      ) order by h.dia_semana)
      from public.horarios_funcionamento h
      where h.id_empresa = sp.id_empresa and h.id_unidade = ue.id and h.ativo
    ), '[]'::jsonb) else '[]'::jsonb end,
    'servicos', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', s.id,
        'nome', s.nome,
        'descricao', s.descricao,
        'preco', case when sp.mostrar_precos then s.preco else null end,
        'duracao_minutos', s.duracao_minutos,
        'intervalo_minutos', s.intervalo_minutos,
        'exige_sinal', s.exige_sinal,
        'sinal_tipo', s.sinal_tipo,
        'sinal_valor', case when sp.mostrar_precos then s.sinal_valor else null end
      ) order by s.nome)
      from public.servicos s
      where s.id_empresa = sp.id_empresa and s.ativo and s.permite_agendamento_online
    ), '[]'::jsonb),
    'profissionais', case when sp.mostrar_profissionais then coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', f.id,
        'nome', regexp_replace(f.nome, '[[:space:]]*\\(Teste\\)[[:space:]]*$', '', 'i'),
        'cargo', coalesce(f.cargo, 'Profissional'),
        'cor_agenda', f.cor_agenda,
        'servicos', coalesce((
          select jsonb_agg(s.id order by s.nome)
          from public.servicos s
          left join public.funcionarios_servicos fs
            on fs.id_empresa = f.id_empresa and fs.id_funcionario = f.id
           and fs.id_servico = s.id and fs.ativo
          where s.id_empresa = f.id_empresa and s.ativo and s.permite_agendamento_online
            and (not exists (
              select 1 from public.funcionarios_servicos configuracao
              where configuracao.id_empresa = f.id_empresa and configuracao.id_funcionario = f.id
            ) or fs.id is not null)
        ), '[]'::jsonb)
      ) order by f.nome)
      from public.funcionarios f
      where f.id_empresa = sp.id_empresa and f.ativo and f.atende_clientes
    ), '[]'::jsonb) else '[]'::jsonb end,
    'avaliacoes', case when sp.mostrar_avaliacoes then coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', a.id,
        'nota', a.nota,
        'comentario', a.comentario,
        'nome', coalesce(nullif(a.nome_publico, ''), split_part(c.nome, ' ', 1)),
        'created_at', a.created_at
      ) order by a.destaque desc, a.created_at desc)
      from public.avaliacoes a
      left join public.clientes c on c.id_empresa = a.id_empresa and c.id = a.id_cliente
      where a.id_empresa = sp.id_empresa
        and a.status = 'aprovada'
        and a.autorizado_publicacao
        and nullif(btrim(a.comentario), '') is not null
    ), '[]'::jsonb) else '[]'::jsonb end
  )
  from site_escolhido sp
  join public.empresas e on e.id = sp.id_empresa
  left join unidade_escolhida ue on true
  left join public.configuracoes_empresas ce on ce.id_empresa = sp.id_empresa;
$$;

create or replace function public.resolver_site_publico(
  p_dominio text default null,
  p_slug text default null
)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select private.resolver_site_publico(p_dominio, p_slug);
$$;

revoke all on function private.salvar_site_publico(bigint, jsonb) from public, anon;
grant execute on function private.salvar_site_publico(bigint, jsonb) to authenticated;
revoke all on function public.salvar_site_publico(bigint, jsonb) from public, anon;
grant execute on function public.salvar_site_publico(bigint, jsonb) to authenticated;

revoke all on function private.resolver_site_publico(text, text) from public;
grant execute on function private.resolver_site_publico(text, text) to anon, authenticated;
revoke all on function public.resolver_site_publico(text, text) from public;
grant execute on function public.resolver_site_publico(text, text) to anon, authenticated;

grant select, insert, update, delete on public.sites_publicos to authenticated;
grant select, insert, update, delete on public.sites_publicos_dominios to authenticated;
grant select, insert, update on public.avaliacoes to authenticated;
grant usage, select on sequence public.sites_publicos_id_seq to authenticated;
grant usage, select on sequence public.sites_publicos_dominios_id_seq to authenticated;
grant usage, select on sequence public.avaliacoes_id_seq to authenticated;

-- Conteudo inicial do exemplo Murakami. Depois desta migration, tudo pode ser
-- alterado pelo painel sem novo deploy e sem fallback ficticio no Next.js.
with empresa_demo as (
  select e.id
  from public.empresas e
  where e.id = 10 or lower(e.fantasia) = 'murakami beauty'
  order by (e.id = 10) desc
  limit 1
), unidade_demo as (
  select u.id_empresa, u.id
  from public.unidades u
  join empresa_demo e on e.id = u.id_empresa
  where u.ativo
  order by u.principal desc, u.id
  limit 1
)
insert into public.sites_publicos (
  id_empresa, id_unidade_principal, slug, publicado, nome_publico,
  titulo_hero, destaque_hero, descricao_hero, titulo_sobre,
  descricao_sobre, imagem_hero_url, imagem_compartilhamento_url,
  instagram_url, whatsapp, email_publico, texto_rodape, titulo_seo,
  descricao_seo, palavras_chave, diferenciais, perguntas_frequentes,
  mostrar_precos, mostrar_profissionais, mostrar_avaliacoes,
  mostrar_endereco, mostrar_horarios
)
select
  e.id, u.id, 'murakami-beauty', true, 'Murakami Beauty',
  'Beleza que respeita', 'quem você é.',
  'Técnica e cuidado se encontram para criar uma experiência leve, personalizada e simples de agendar.',
  'Mais do que beleza. Uma experiência.',
  'Um espaço onde técnica, escuta e cuidado se encontram. Cada atendimento começa entendendo seu estilo, sua rotina e o que faz sentido agora.',
  '/images/hero-murakami.png', '/og.png',
  'https://instagram.com/murakamibeauty', '(11) 90000-0010', null,
  'Beleza com intenção, cuidado e tempo para você.',
  'Murakami Beauty | Salão de beleza em São Paulo',
  'Serviços de beleza com atendimento personalizado e agendamento online.',
  array['salão de beleza São Paulo', 'agendamento online', 'Murakami Beauty'],
  '["Produtos profissionais e protocolos personalizados", "Especialistas em constante aperfeiçoamento", "Atendimento acolhedor e organizado"]'::jsonb,
  '[{"pergunta":"Como funciona o agendamento online?","resposta":"Escolha o serviço, profissional, dia e horário. Depois confirme seus dados em poucos minutos."},{"pergunta":"Preciso pagar para reservar?","resposta":"Quando houver sinal, o valor e as condições aparecem antes da confirmação."},{"pergunta":"Posso remarcar ou cancelar?","resposta":"Sim. Use a Área do Cliente dentro das regras informadas no agendamento."},{"pergunta":"Vocês enviam lembrete?","resposta":"Sim. As preferências de WhatsApp e e-mail podem ser definidas no agendamento."}]'::jsonb,
  true, true, false, true, true
from empresa_demo e
left join unidade_demo u on u.id_empresa = e.id
on conflict (id_empresa) do nothing;

insert into public.sites_publicos_dominios (id_site, id_empresa, dominio, principal)
select sp.id, sp.id_empresa, d.dominio, d.principal
from public.sites_publicos sp
cross join (values
  ('localhost'::text, true),
  ('127.0.0.1'::text, false),
  ('murakami-beauty.vercel.app'::text, false)
) as d(dominio, principal)
where sp.slug = 'murakami-beauty'
on conflict (dominio) do nothing;

update public.unidades u
set endereco = coalesce(nullif(u.endereco, ''), 'Alameda das Flores'),
    numero = coalesce(nullif(u.numero, ''), '110'),
    bairro = coalesce(nullif(u.bairro, ''), 'Jardins'),
    cidade = coalesce(nullif(u.cidade, ''), 'São Paulo'),
    estado = coalesce(nullif(u.estado, ''), 'SP'),
    cep = coalesce(nullif(u.cep, ''), '01400-000'),
    telefone = coalesce(nullif(u.telefone, ''), '(11) 90000-0010'),
    updated_at = now()
where u.id = (
  select sp.id_unidade_principal
  from public.sites_publicos sp
  where sp.slug = 'murakami-beauty'
);

do $$
begin
  if not exists (
    select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'sites_publicos' and c.relrowsecurity
  ) or not exists (
    select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'avaliacoes' and c.relrowsecurity
  ) then
    raise exception 'RLS não foi ativada nas tabelas do site público.';
  end if;
end;
$$;
