-- Fase 13: autenticacao passwordless e autosservico seguro do cliente.
-- A conta Auth so e vinculada quando o e-mail confirmado coincide com um
-- unico cadastro ativo da empresa. Toda leitura e mutacao valida auth.uid().

create table if not exists public.solicitacoes_privacidade (
  id bigint generated by default as identity primary key,
  id_empresa bigint not null,
  id_cliente bigint not null,
  tipo text not null default 'exclusao',
  status text not null default 'pendente',
  motivo text,
  solicitado_em timestamptz not null default now(),
  processado_em timestamptz,
  processado_por uuid,
  observacoes_internas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint solicitacoes_privacidade_cliente_fkey
    foreign key (id_empresa, id_cliente)
    references public.clientes(id_empresa, id) on delete restrict,
  constraint solicitacoes_privacidade_tipo_check
    check (tipo in ('exclusao', 'exportacao', 'correcao')),
  constraint solicitacoes_privacidade_status_check
    check (status in ('pendente', 'em_analise', 'concluida', 'recusada', 'cancelada'))
);
create unique index if not exists solicitacoes_privacidade_exclusao_pendente_unique
  on public.solicitacoes_privacidade (id_empresa, id_cliente, tipo)
  where tipo = 'exclusao' and status in ('pendente', 'em_analise');
create index if not exists solicitacoes_privacidade_empresa_status_idx
  on public.solicitacoes_privacidade (id_empresa, status, solicitado_em desc);
alter table public.solicitacoes_privacidade enable row level security;
drop policy if exists solicitacoes_privacidade_cliente_le_proprias
  on public.solicitacoes_privacidade;
create policy solicitacoes_privacidade_cliente_le_proprias
on public.solicitacoes_privacidade for select to authenticated
using (private.usuario_eh_cliente(id_empresa, id_cliente));
drop policy if exists solicitacoes_privacidade_gestao_gerencia
  on public.solicitacoes_privacidade;
create policy solicitacoes_privacidade_gestao_gerencia
on public.solicitacoes_privacidade for all to authenticated
using (private.usuario_tem_tipo_empresa(
  id_empresa, array['dono', 'gerente']::public.tipos_usuarios[]
))
with check (private.usuario_tem_tipo_empresa(
  id_empresa, array['dono', 'gerente']::public.tipos_usuarios[]
));
grant select, update on public.solicitacoes_privacidade to authenticated;
create or replace function private.vincular_cliente_email_site(
  p_id_empresa bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text := lower(btrim(coalesce(auth.jwt() ->> 'email', '')));
  v_id_cliente bigint;
  v_total integer;
  v_auth_conflitante boolean;
begin
  if auth.uid() is null or v_email = '' then
    raise exception 'Autenticacao por e-mail obrigatoria.';
  end if;

  select
    count(*),
    bool_or(c.auth_user_id is not null and c.auth_user_id <> auth.uid())
    into v_total, v_auth_conflitante
  from public.clientes c
  where c.id_empresa = p_id_empresa
    and c.ativo
    and lower(btrim(coalesce(c.email, ''))) = v_email;

  if coalesce(v_auth_conflitante, false) then
    raise exception 'Este e-mail ja esta associado a outra conta. Fale com a recepcao.';
  end if;
  if v_total = 0 then
    raise exception 'Nao encontramos um cadastro de cliente com este e-mail.';
  end if;
  if v_total > 1 then
    raise exception 'Ha cadastros duplicados com este e-mail. Fale com a recepcao para unifica-los.';
  end if;

  select c.id into v_id_cliente
  from public.clientes c
  where c.id_empresa = p_id_empresa
    and c.ativo
    and lower(btrim(coalesce(c.email, ''))) = v_email
  for update;

  update public.clientes
  set auth_user_id = auth.uid(), updated_at = now()
  where id_empresa = p_id_empresa
    and id = v_id_cliente
    and (auth_user_id is null or auth_user_id = auth.uid());

  return jsonb_build_object('vinculado', true, 'id_cliente', v_id_cliente);
end;
$$;
create or replace function private.obter_area_cliente_site(
  p_id_empresa bigint
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_cliente public.clientes%rowtype;
  v_empresa_nome text;
  v_resultado jsonb;
begin
  if auth.uid() is null then
    raise exception 'Autenticacao do cliente obrigatoria.';
  end if;

  select c.* into v_cliente
  from public.clientes c
  where c.id_empresa = p_id_empresa
    and c.auth_user_id = auth.uid()
    and c.ativo;

  if not found then
    raise exception 'Conta autenticada ainda nao vinculada a um cliente desta empresa.';
  end if;

  select coalesce(e.fantasia, e.razao_social, 'Empresa') into v_empresa_nome
  from public.empresas e
  where e.id = p_id_empresa;

  select jsonb_build_object(
    'empresa', jsonb_build_object(
      'id', p_id_empresa,
      'nome', v_empresa_nome
    ),
    'cliente', jsonb_build_object(
      'id', v_cliente.id,
      'nome', v_cliente.nome,
      'email', v_cliente.email,
      'telefone', v_cliente.telefone_principal,
      'data_nascimento', v_cliente.data_nascimento,
      'canal_preferido', v_cliente.canal_preferido
    ),
    'preferencias', coalesce((
      select jsonb_build_object(
        'whatsapp', p.whatsapp,
        'email', p.email,
        'sms', p.sms,
        'push', p.push,
        'antecedencias_minutos', p.antecedencias_minutos
      )
      from public.preferencias_lembrete p
      where p.id_empresa = p_id_empresa
        and p.id_cliente = v_cliente.id
        and p.ativo
    ), jsonb_build_object(
      'whatsapp', true,
      'email', true,
      'sms', false,
      'push', false,
      'antecedencias_minutos', array[1440, 120]
    )),
    'solicitacao_exclusao', (
      select jsonb_build_object(
        'id', sp.id,
        'status', sp.status,
        'solicitado_em', sp.solicitado_em
      )
      from public.solicitacoes_privacidade sp
      where sp.id_empresa = p_id_empresa
        and sp.id_cliente = v_cliente.id
        and sp.tipo = 'exclusao'
      order by sp.solicitado_em desc
      limit 1
    ),
    'agendamentos', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', a.id,
        'codigo', 'MK' || lpad(a.id::text, 6, '0'),
        'status', a.status,
        'inicio', a.inicio,
        'fim', a.fim,
        'valor_total', a.valor_total,
        'sinal_status', a.sinal_status,
        'sinal_valor', a.sinal_valor,
        'pagamento_status', a.pagamento_status,
        'confirmado_em', a.confirmado_em,
        'cancelado_em', a.cancelado_em,
        'motivo_cancelamento', a.motivo_cancelamento,
        'pode_confirmar', a.status in ('aguardando_confirmacao', 'aguardando_pagamento')
          and a.sinal_status <> 'pendente'
          and a.inicio > now(),
        'pode_cancelar', a.status not in ('cancelado', 'finalizado', 'no_show', 'em_atendimento')
          and a.inicio > now() + make_interval(mins => coalesce(pol.antecedencia_cancelamento_minutos, 1440)),
        'pode_reagendar', a.status not in ('cancelado', 'finalizado', 'no_show', 'em_atendimento')
          and a.inicio > now() + make_interval(mins => coalesce(pol.antecedencia_reagendamento_minutos, 1440)),
        'politica', jsonb_build_object(
          'antecedencia_cancelamento_minutos', coalesce(pol.antecedencia_cancelamento_minutos, 1440),
          'antecedencia_reagendamento_minutos', coalesce(pol.antecedencia_reagendamento_minutos, 1440),
          'texto_publico', pol.texto_publico
        ),
        'servico', jsonb_build_object(
          'id', item.id_servico,
          'nome', s.nome,
          'duracao_minutos', item.duracao_minutos,
          'preco', item.preco
        ),
        'profissional', jsonb_build_object(
          'id', item.id_funcionario,
          'nome', regexp_replace(f.nome, '[[:space:]]*\(Teste\)[[:space:]]*$', '', 'i'),
          'cargo', coalesce(f.cargo, 'Profissional')
        ),
        'unidade', jsonb_build_object(
          'id', u.id,
          'nome', u.nome,
          'bairro', u.bairro,
          'cidade', u.cidade
        ),
        'pagamentos', coalesce((
          select jsonb_agg(jsonb_build_object(
            'id', pg.id,
            'valor', pg.valor,
            'status', pg.status,
            'tipo', pg.tipo,
            'data_pagamento', pg.data_pagamento,
            'provedor', pg.provedor,
            'referencia', pg.referencia
          ) order by pg.data_pagamento desc, pg.id desc)
          from public.pagamentos pg
          where pg.id_empresa = a.id_empresa
            and pg.id_agendamento = a.id
        ), '[]'::jsonb)
      ) order by a.inicio desc, a.id desc)
      from public.agendamentos a
      join lateral (
        select i.*
        from public.agendamentos_servicos i
        where i.id_empresa = a.id_empresa
          and i.id_agendamento = a.id
        order by (i.status <> 'cancelado') desc, i.ordem, i.id
        limit 1
      ) item on true
      join public.servicos s
        on s.id_empresa = item.id_empresa and s.id = item.id_servico
      join public.funcionarios f
        on f.id_empresa = item.id_empresa and f.id = item.id_funcionario
      join public.unidades u
        on u.id_empresa = a.id_empresa and u.id = a.id_unidade
      left join lateral (
        select p.antecedencia_cancelamento_minutos,
               p.antecedencia_reagendamento_minutos,
               p.texto_publico
        from public.politicas_cancelamento p
        where p.id_empresa = a.id_empresa
          and p.ativo
          and current_date between p.vigente_desde and coalesce(p.vigente_ate, 'infinity'::date)
          and (p.id_unidade = a.id_unidade or p.id_unidade is null)
        order by (p.id_unidade = a.id_unidade) desc, p.vigente_desde desc, p.id desc
        limit 1
      ) pol on true
      where a.id_empresa = p_id_empresa
        and a.id_cliente = v_cliente.id
    ), '[]'::jsonb)
  ) into v_resultado;

  return v_resultado;
end;
$$;
create or replace function private.atualizar_dados_cliente_site(
  p_id_empresa bigint,
  p_nome text,
  p_telefone text,
  p_data_nascimento date default null,
  p_canal_preferido text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_nome text := btrim(coalesce(p_nome, ''));
  v_telefone_numeros text := regexp_replace(coalesce(p_telefone, ''), '[^0-9]', '', 'g');
begin
  if auth.uid() is null then
    raise exception 'Autenticacao do cliente obrigatoria.';
  end if;
  if char_length(v_nome) < 2 or char_length(v_nome) > 120 then
    raise exception 'Informe um nome valido.';
  end if;
  if char_length(v_telefone_numeros) < 10 or char_length(v_telefone_numeros) > 13 then
    raise exception 'Informe um telefone valido com DDD.';
  end if;
  if p_data_nascimento is not null and (p_data_nascimento > current_date or p_data_nascimento < current_date - interval '120 years') then
    raise exception 'Informe uma data de nascimento valida.';
  end if;
  if p_canal_preferido is not null and p_canal_preferido not in ('whatsapp', 'email', 'sms', 'telefone') then
    raise exception 'Canal de contato invalido.';
  end if;

  update public.clientes
  set nome = v_nome,
      telefone_principal = p_telefone,
      telefone_e164 = case
        when v_telefone_numeros like '55%' then '+' || v_telefone_numeros
        else '+55' || v_telefone_numeros
      end,
      data_nascimento = p_data_nascimento,
      canal_preferido = p_canal_preferido,
      updated_at = now()
  where id_empresa = p_id_empresa
    and auth_user_id = auth.uid()
    and ativo;

  if not found then
    raise exception 'Cliente autenticado nao encontrado.';
  end if;

  return private.obter_area_cliente_site(p_id_empresa);
end;
$$;
create or replace function private.atualizar_preferencias_cliente_site(
  p_id_empresa bigint,
  p_whatsapp boolean,
  p_email boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id_cliente bigint;
begin
  select c.id into v_id_cliente
  from public.clientes c
  where c.id_empresa = p_id_empresa
    and c.auth_user_id = auth.uid()
    and c.ativo;

  if v_id_cliente is null then
    raise exception 'Cliente autenticado nao encontrado.';
  end if;

  insert into public.preferencias_lembrete (
    id_empresa, id_cliente, whatsapp, email, sms, push,
    antecedencias_minutos, ativo, origem, updated_at
  ) values (
    p_id_empresa, v_id_cliente, p_whatsapp, p_email, false, false,
    array[1440, 120], true, 'site_cliente', now()
  )
  on conflict (id_empresa, id_cliente) do update
    set whatsapp = excluded.whatsapp,
        email = excluded.email,
        ativo = true,
        origem = 'site_cliente',
        updated_at = now();

  return private.obter_area_cliente_site(p_id_empresa);
end;
$$;
create or replace function private.alterar_agendamento_cliente_site(
  p_id_empresa bigint,
  p_id_agendamento bigint,
  p_acao text,
  p_motivo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_agendamento public.agendamentos%rowtype;
  v_antecedencia_cancelamento integer := 1440;
begin
  select a.* into v_agendamento
  from public.agendamentos a
  join public.clientes c
    on c.id_empresa = a.id_empresa and c.id = a.id_cliente
  where a.id_empresa = p_id_empresa
    and a.id = p_id_agendamento
    and c.auth_user_id = auth.uid()
    and c.ativo
  for update of a;

  if not found then
    raise exception 'Agendamento nao encontrado para este cliente.';
  end if;

  if p_acao = 'confirmar' then
    if v_agendamento.status not in ('aguardando_confirmacao', 'aguardando_pagamento') then
      raise exception 'Este agendamento nao pode ser confirmado.';
    end if;
    if v_agendamento.sinal_status = 'pendente' then
      raise exception 'O pagamento do sinal ainda esta pendente.';
    end if;
    if v_agendamento.inicio <= now() then
      raise exception 'Agendamentos passados nao podem ser confirmados.';
    end if;

    update public.agendamentos
    set status = 'confirmado'
    where id_empresa = p_id_empresa and id = p_id_agendamento;
  elsif p_acao = 'cancelar' then
    if v_agendamento.status in ('cancelado', 'finalizado', 'no_show', 'em_atendimento') then
      raise exception 'Este agendamento nao pode mais ser cancelado.';
    end if;

    select coalesce(p.antecedencia_cancelamento_minutos, 1440)
      into v_antecedencia_cancelamento
    from public.politicas_cancelamento p
    where p.id_empresa = p_id_empresa
      and p.ativo
      and current_date between p.vigente_desde and coalesce(p.vigente_ate, 'infinity'::date)
      and (p.id_unidade = v_agendamento.id_unidade or p.id_unidade is null)
    order by (p.id_unidade = v_agendamento.id_unidade) desc, p.vigente_desde desc, p.id desc
    limit 1;

    if v_agendamento.inicio <= now() + make_interval(mins => coalesce(v_antecedencia_cancelamento, 1440)) then
      raise exception 'O prazo para cancelamento online desta reserva ja terminou.';
    end if;

    update public.agendamentos
    set status = 'cancelado',
        motivo_cancelamento = coalesce(nullif(btrim(p_motivo), ''), 'Cancelado pelo cliente na area autenticada.')
    where id_empresa = p_id_empresa and id = p_id_agendamento;
  else
    raise exception 'Acao invalida.';
  end if;

  return private.obter_area_cliente_site(p_id_empresa);
end;
$$;
create or replace function private.reagendar_agendamento_cliente_site(
  p_id_empresa bigint,
  p_id_agendamento bigint,
  p_id_funcionario bigint,
  p_inicio timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_token uuid;
begin
  select a.site_access_token into v_token
  from public.agendamentos a
  join public.clientes c
    on c.id_empresa = a.id_empresa and c.id = a.id_cliente
  where a.id_empresa = p_id_empresa
    and a.id = p_id_agendamento
    and c.auth_user_id = auth.uid()
    and c.ativo
  for update of a;

  if not found then
    raise exception 'Agendamento nao encontrado para este cliente.';
  end if;

  if v_token is null then
    v_token := gen_random_uuid();
    update public.agendamentos
    set site_access_token = v_token
    where id_empresa = p_id_empresa and id = p_id_agendamento;
  end if;

  perform private.reagendar_agendamento_site(v_token, p_id_funcionario, p_inicio);
  return private.obter_area_cliente_site(p_id_empresa);
end;
$$;
create or replace function private.solicitar_exclusao_dados_site(
  p_id_empresa bigint,
  p_motivo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id_cliente bigint;
begin
  select c.id into v_id_cliente
  from public.clientes c
  where c.id_empresa = p_id_empresa
    and c.auth_user_id = auth.uid()
    and c.ativo;

  if v_id_cliente is null then
    raise exception 'Cliente autenticado nao encontrado.';
  end if;
  if char_length(coalesce(p_motivo, '')) > 500 then
    raise exception 'O motivo pode ter no maximo 500 caracteres.';
  end if;

  insert into public.solicitacoes_privacidade (
    id_empresa, id_cliente, tipo, status, motivo
  ) values (
    p_id_empresa, v_id_cliente, 'exclusao', 'pendente', nullif(btrim(p_motivo), '')
  )
  on conflict (id_empresa, id_cliente, tipo)
    where tipo = 'exclusao' and status in ('pendente', 'em_analise')
  do update set updated_at = now();

  return private.obter_area_cliente_site(p_id_empresa);
end;
$$;
revoke all on function private.vincular_cliente_email_site(bigint) from public, anon, authenticated;
revoke all on function private.obter_area_cliente_site(bigint) from public, anon, authenticated;
revoke all on function private.atualizar_dados_cliente_site(bigint, text, text, date, text) from public, anon, authenticated;
revoke all on function private.atualizar_preferencias_cliente_site(bigint, boolean, boolean) from public, anon, authenticated;
revoke all on function private.alterar_agendamento_cliente_site(bigint, bigint, text, text) from public, anon, authenticated;
revoke all on function private.reagendar_agendamento_cliente_site(bigint, bigint, bigint, timestamptz) from public, anon, authenticated;
revoke all on function private.solicitar_exclusao_dados_site(bigint, text) from public, anon, authenticated;
grant execute on function private.vincular_cliente_email_site(bigint) to authenticated;
grant execute on function private.obter_area_cliente_site(bigint) to authenticated;
grant execute on function private.atualizar_dados_cliente_site(bigint, text, text, date, text) to authenticated;
grant execute on function private.atualizar_preferencias_cliente_site(bigint, boolean, boolean) to authenticated;
grant execute on function private.alterar_agendamento_cliente_site(bigint, bigint, text, text) to authenticated;
grant execute on function private.reagendar_agendamento_cliente_site(bigint, bigint, bigint, timestamptz) to authenticated;
grant execute on function private.solicitar_exclusao_dados_site(bigint, text) to authenticated;
create or replace function public.vincular_cliente_email_site(p_id_empresa bigint)
returns jsonb language sql volatile security invoker set search_path = ''
as $$ select private.vincular_cliente_email_site($1) $$;
create or replace function public.obter_area_cliente_site(p_id_empresa bigint)
returns jsonb language sql stable security invoker set search_path = ''
as $$ select private.obter_area_cliente_site($1) $$;
create or replace function public.atualizar_dados_cliente_site(
  p_id_empresa bigint, p_nome text, p_telefone text,
  p_data_nascimento date default null, p_canal_preferido text default null
)
returns jsonb language sql volatile security invoker set search_path = ''
as $$ select private.atualizar_dados_cliente_site($1, $2, $3, $4, $5) $$;
create or replace function public.atualizar_preferencias_cliente_site(
  p_id_empresa bigint, p_whatsapp boolean, p_email boolean
)
returns jsonb language sql volatile security invoker set search_path = ''
as $$ select private.atualizar_preferencias_cliente_site($1, $2, $3) $$;
create or replace function public.alterar_agendamento_cliente_site(
  p_id_empresa bigint, p_id_agendamento bigint,
  p_acao text, p_motivo text default null
)
returns jsonb language sql volatile security invoker set search_path = ''
as $$ select private.alterar_agendamento_cliente_site($1, $2, $3, $4) $$;
create or replace function public.reagendar_agendamento_cliente_site(
  p_id_empresa bigint, p_id_agendamento bigint,
  p_id_funcionario bigint, p_inicio timestamptz
)
returns jsonb language sql volatile security invoker set search_path = ''
as $$ select private.reagendar_agendamento_cliente_site($1, $2, $3, $4) $$;
create or replace function public.solicitar_exclusao_dados_site(
  p_id_empresa bigint, p_motivo text default null
)
returns jsonb language sql volatile security invoker set search_path = ''
as $$ select private.solicitar_exclusao_dados_site($1, $2) $$;
revoke all on function public.vincular_cliente_email_site(bigint) from public, anon, authenticated;
revoke all on function public.obter_area_cliente_site(bigint) from public, anon, authenticated;
revoke all on function public.atualizar_dados_cliente_site(bigint, text, text, date, text) from public, anon, authenticated;
revoke all on function public.atualizar_preferencias_cliente_site(bigint, boolean, boolean) from public, anon, authenticated;
revoke all on function public.alterar_agendamento_cliente_site(bigint, bigint, text, text) from public, anon, authenticated;
revoke all on function public.reagendar_agendamento_cliente_site(bigint, bigint, bigint, timestamptz) from public, anon, authenticated;
revoke all on function public.solicitar_exclusao_dados_site(bigint, text) from public, anon, authenticated;
grant execute on function public.vincular_cliente_email_site(bigint) to authenticated;
grant execute on function public.obter_area_cliente_site(bigint) to authenticated;
grant execute on function public.atualizar_dados_cliente_site(bigint, text, text, date, text) to authenticated;
grant execute on function public.atualizar_preferencias_cliente_site(bigint, boolean, boolean) to authenticated;
grant execute on function public.alterar_agendamento_cliente_site(bigint, bigint, text, text) to authenticated;
grant execute on function public.reagendar_agendamento_cliente_site(bigint, bigint, bigint, timestamptz) to authenticated;
grant execute on function public.solicitar_exclusao_dados_site(bigint, text) to authenticated;
do $$
begin
  if not (select relrowsecurity from pg_class where oid = 'public.solicitacoes_privacidade'::regclass) then
    raise exception 'RLS nao foi ativada em solicitacoes_privacidade.';
  end if;
  if has_function_privilege('anon', 'public.obter_area_cliente_site(bigint)', 'EXECUTE') then
    raise exception 'A area do cliente ficou acessivel para anon.';
  end if;
  if exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'vincular_cliente_email_site', 'obter_area_cliente_site',
        'atualizar_dados_cliente_site', 'atualizar_preferencias_cliente_site',
        'alterar_agendamento_cliente_site', 'reagendar_agendamento_cliente_site',
        'solicitar_exclusao_dados_site'
      )
      and p.prosecdef
  ) then
    raise exception 'Uma RPC de cliente SECURITY DEFINER ficou exposta no schema public.';
  end if;
end;
$$;
comment on table public.solicitacoes_privacidade is
  'Solicitacoes LGPD do cliente; exclusao e analisada antes de remover dados com retencao obrigatoria.';
comment on function public.vincular_cliente_email_site(bigint) is
  'Vincula a conta Auth ao unico cliente ativo com o mesmo e-mail confirmado na empresa.';
comment on function public.obter_area_cliente_site(bigint) is
  'Retorna somente os dados, agendamentos, pagamentos e preferencias do cliente autenticado.';
